### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by RahulDey12** [atom/settings-view#1029]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\RAHUL\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:240

TypeError: Cannot read property 'version' of undefined
    at /app.asar/node_modules/settings-view/lib/package-card.js:240:34
    at /app.asar/node_modules/settings-view/lib/package-manager.js:282:18
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:22.4.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:06.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
You are on an outdated version of Atom - please update to the latest version, currently Atom 1.23.1, at https://atom.io
