### ISSUE TITLE
Can't install packages or themes or view featured packages/themes

### ISSUE THREAD

**Issue by capybar** [atom/settings-view#1041]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
I can't even get into safe mode as atom is not recognized as an internal or external command
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
Ofcourse, I also couldn't follow the steps for debugging because of previous reason
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I am unable to install packages or themes on Atom. I can't even view the featured themes or packages.
I keep getting this message:
`module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\Users\Me\AppData\Local\atom\app-1.23.3\resources\app\apm\lib\cli.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

### Steps to Reproduce

1. I tried uninstalling it and reinstalling it
2. Tried to manually set a path 
3. Installed node.js because previously it said node.js was not detected
4. Tried to debug, use atom in safe mode but atom wasn't recognized in command line

**Expected behavior:** [What you expect to happen]
I thought step 2 would fix the problem but it didn't. Step 3 just caused a different problem

**Actual behavior:** [What actually happens]
It continued not being able to install or view themes/packages
**Reproduces how often:** [What percentage of the time does it reproduce?]
I've tried this over 5 times and it produced the same result

### Versions
Atom:1.23.3
Node:8.9.4
Windows 10

### Additional Information
I haven't made any changes to Atom when I re-installed it. I'm not really familiar with node. This is a new problem for me. Packages and themes were easily installable in previous version of Atom.

**Comment by 50Wliu** [comment]
Does the file `C:\Users\Me\AppData\Local\atom\app-1.23.3\resources\app\apm\lib\cli.js` exist?

**Comment by bogdanostojic** [comment]
Hey, I had a similar issue. The problem was I had a  `!` in my username on the computer.
Does your user name on Windows 10 machine contain characters other then numbers or letters?
I see you put in `C:\Users\Me\...` 
Check out the issue I had, hope it helps. #951

**Comment by dumb-stuff** [comment]
I am have that problem too.
