### ISSUE TITLE
Failed to activate the settings-view package

### ISSUE THREAD

**Issue by DragonLaggin** [atom/settings-view#1046]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.253.1-0

### Stack Trace

Failed to activate the settings-view package

```
At Invalid Point: (NaN, 0)

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:345:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateToBufferMarkerLayerFindParams (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:253:59)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.findMarkers (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:141:27)
    at TextEditor.findMarkers (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:2360:42)
    at ColorBuffer.module.exports.ColorBuffer.findColorMarkers (/packages/pigments/lib/color-buffer.coffee:333:23)
    at ColorBuffer.module.exports.ColorBuffer.findValidColorMarkers (/packages/pigments/lib/color-buffer.coffee:339:6)
    at HTMLElement.ColorBufferElement.updateMarkers (/packages/pigments/lib/color-buffer-element.coffee:143:28)
    at HTMLElement.ColorBufferElement.editorConfigChanged (/packages/pigments/lib/color-buffer-element.coffee:119:6)
    at /packages/pigments/lib/color-buffer-element.coffee:83:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at StyleManager.addStyleElement (~/AppData/Local/atom/app-1.24.0/resources/app/src/style-manager.js:190:24)
    at StyleManager.addStyleSheet (~/AppData/Local/atom/app-1.24.0/resources/app/src/style-manager.js:169:18)
    at Package.activateStylesheets (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:288:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:223:18)
    at measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:200:20)
    at Package.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.24.0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.24.0/resources/app/src/atom-environment.js:841:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-flat-ui 1.1.0 
atom-ide-ui 0.8.1 
atom-xterm 6.2.0 
ide-html 0.4.1 
linter 1.8.1 
linter-gcc 0.3.8 
minimap 4.29.7 
monokai 0.18.0 
monokai-flat 1.0.1 
pigments 0.18.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [pigments](https://atom.io/packages/pigments) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
