### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEqual' of undefined

### ISSUE THREAD

**Issue by mrlizzard** [atom/settings-view#1048]
[Enter steps to reproduce:]

1. Open settings menu with `CTRL + Comma`
2. Go to "Editor" tab
3. Change the tabulation length (change '4' to '8')

**Atom**: 1.24.0 x64
**Electron**: 1.8.2
**OS**: "Arch Linux"
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.253.1-0

### Stack Trace

Uncaught TypeError: Cannot read property 'isEqual' of undefined

```
At /usr/lib/atom/src/text-editor-registry.js:233

TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (/usr/lib/atom/src/text-editor-registry.js:233:50)
    at Set.forEach (native)
    at subscriptions.add.config.onDidChange (/usr/lib/atom/src/text-editor-registry.js:232:46)
    at /usr/lib/atom/src/config.js:953:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/lib/atom/src/config.js:882:29)
    at Config.module.exports.Config.setRawValue (/usr/lib/atom/src/config.js:668:19)
    at Config.module.exports.Config.set (/usr/lib/atom/src/config.js:246:14)
    at SettingsPanel.set (/usr/lib/atom/node_modules/settings-view/lib/settings-panel.js:233:21)
    at /usr/lib/atom/node_modules/settings-view/lib/settings-panel.js:311:18
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1706:20)
    at later (/usr/lib/atom/node_modules/text-buffer/lib/helpers.js:23:7)
```

### Commands

```
     -0:25.2.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-electron-highlighter-syntax.theme-one-dark-ui)
     -0:13.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
autocomplete-clang 0.11.4 
busy-signal 1.4.3 
electron-highlighter-syntax 1.16.0 
epitech-header-2018 2.3.10 
file-icons 2.1.17 
formatter-coffeescript 0.1.1 
intentions 1.1.5 
linter 2.2.0 
linter-clang 4.1.2 
linter-coffeescript 1.0.0 
linter-ui-default 1.7.0 
markdown-toc 0.4.2 
minimap 4.29.8 
open-terminal-here 2.3.1 
todo-show 2.2.0 
```

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by mrlizzard** [comment]
Yes I've download Atom on my arch distribution with yaourt package manager... And is an unofficial build.

Thank's a lot!
