### ISSUE TITLE
"Body.filter ist not a function"

### ISSUE THREAD

**Issue by Zinnig** [atom/settings-view#1064]
[Enter steps to reproduce:]

1. search for a theme or for a package (so it happend)
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: IPC
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.254.2

### Stack Trace

Uncaught TypeError: body.filter is not a function

```
At C:\Users\Felix\AppData\Local\atom\app-1.28.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:305

TypeError: body.filter is not a function
    at Request._callback (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:51.4.0 core:confirm (input.hidden-input)
  3x -0:21.4.0 core:backspace (input.hidden-input)
     -0:19.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.12.0 
busy-signal 1.4.3 
color-picker 2.3.0 
file-icons 2.1.21 
Hydrogen 2.5.1 
ide-cpp 0.0.3 
ide-csharp 0.6.2 
ide-css 0.3.0 
ide-html 0.4.2 
ide-java 0.8.3 
ide-json 0.2.1 
ide-php 0.7.14 
ide-python 1.0.0 
intentions 1.1.5 
java-importer 1.4.1 
linter 2.2.0 
linter-javac 1.9.4 
linter-spell-javascript 0.9.0 
linter-ui-default 1.7.1 
```

**Comment by Bligivi** [comment]
Hello,

I have the same problem and when I go to "https://atom.io" it is written : 

"Offline for maintenance
This app is undergoing maintenance right now.
Please check back later."

I think it's related ;)

**Comment by rsese** [comment]
Thanks for the report @Zinnig - if you tried search between 13:00-15:00 UTC yesterday, then this is likely related to the scheduled maintenance @Bligivi mentioned /cc https://discuss.atom.io/t/scheduled-maintenance-of-atom-io-from-1300-utc-on-sunday-june-24/56230.

Going to go ahead and close but if you're still having this issue please let us know.
