### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by owlMTY** [atom/settings-view#1070]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.255.0

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At C:\Users\lenovo\AppData\Local\atom\app-1.29.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:121

TypeError: Cannot convert undefined or null to object
    at Request._callback (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:121:17)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
emmet 2.4.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
