### ISSUE TITLE
Failed to reload the settings-view package stylesheets

### ISSUE THREAD

**Issue by Srihariaditha** [atom/settings-view#1142]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 16.04.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.261.3

### Stack Trace

Failed to reload the settings-view package stylesheets

```
At errmap.get is not a function or its return value is not iterable

TypeError: errmap.get is not a function or its return value is not iterable
    at Object.uvException (internal/errors.js:251:34)
    at handleErrorFromBinding (fs.js:113:24)
    at Object.closeSync (fs.js:401:3)
    at Object.closeSync (/app.asar/node_modules/graceful-fs/graceful-fs.js:51:27)
    at Object.writeFileSync (fs.js:1186:23)
    at Proxy.writeFileSync (/usr/share/atom/resources/app/static/<embedded>:11:269454)
    at LessCache.writeJson (/usr/share/atom/resources/app/static/<embedded>:14:1151522)
    at LessCache.putCachedCss (/usr/share/atom/resources/app/static/<embedded>:14:1153005)
    at LessCache.cssForFile (/usr/share/atom/resources/app/static/<embedded>:14:1153981)
    at LessCompileCache.cssForFile (/usr/share/atom/resources/app/static/<embedded>:14:14087)
    at ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app/static/<embedded>:11:391036)
    at ThemeManager.loadStylesheet (/usr/share/atom/resources/app/static/<embedded>:11:390393)
    at stylesheets.getStylesheetPaths.map.e (/usr/share/atom/resources/app/static/<embedded>:11:3217724)
    at Array.map (<anonymous>)
    at Package.loadStylesheets (/usr/share/atom/resources/app/static/<embedded>:11:3217696)
    at Package.reloadStylesheets (/usr/share/atom/resources/app/static/<embedded>:11:3223390)
    at PackageManager.reloadActivePackageStyleSheets (/usr/share/atom/resources/app/static/<embedded>:11:384694)
    at onDidChangeActiveThemes (/usr/share/atom/resources/app/static/<embedded>:11:386649)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1214427)
    at Promise.all.then (/usr/share/atom/resources/app/static/<embedded>:11:392271)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
docker 0.8.0 
```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
