### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by fahaxiki-net** [atom/settings-view#1152]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.12
**OS**: "Manjaro Linux"
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.261.3

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /usr/lib/atom/node_modules/settings-view/lib/package-card.js:235

TypeError: Cannot read property 'version' of undefined
    at /usr/lib/atom/node_modules/settings-view/lib/package-card.js:235:35
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:319:18
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:280:9)
    at bufferStream (/usr/lib/atom/src/buffered-process.js:301:9)
    at Socket.stream.on (/usr/lib/atom/src/buffered-process.js:169:7)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -4:46.6.0 core:confirm (input.hidden-input)
     -3:50.1.0 tree-view:move (span.name.icon.icon-book)
     -3:48.5.0 core:select-all (input.hidden-input)
     -3:47.8.0 core:paste (input.hidden-input)
     -3:46.6.0 core:confirm (input.hidden-input)
  2x -3:44.7.0 core:backspace (input.hidden-input)
     -3:44.1.0 core:save (input.hidden-input)
     -1:39 command-palette:toggle (div.tool-panel.tree-view)
  5x -1:36.5.0 core:backspace (input.hidden-input)
  8x -1:27.6.0 core:move-down (input.hidden-input)
     -1:25.4.0 core:move-up (input.hidden-input)
     -1:25.1.0 core:confirm (input.hidden-input)
     -1:25.1.0 settings-view:view-installed-packages (div.tool-panel.tree-view)
     -0:44.9.0 markdown-preview:toggle (input.hidden-input)
  5x -0:42.3.0 core:backspace (input.hidden-input)
  2x -0:09.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by dzbyr** [comment]
I have same issue, same OS but newer version
```
Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```

**Comment by AmphoMoronal** [comment]
I can´t solve the problem with installing nodejs (Same OS btw). Maybe its a bug or some like that?? 
Have you other ideas how to fix that?

**Comment by aceventura82** [comment]
Hello,

I'm having the same problem, also in Manjaro
While it's fixed I am using Atom beta and it's Working
yay -S atom-editor-beta-bin

**Comment by dzbyr** [comment]
Mine broke again.
I think this is so stable on instability. 
I deleted and go to @aceventura82 's suggest  thanks
This is works now

**Comment by madbullahi** [comment]
Hello ,
I am having issues installing this. Any advice on how to go about this?
