### ISSUE TITLE
Cannot Install Packages! (Node.js, apm)

### ISSUE THREAD

**Issue by yiweed** [atom/settings-view#1157]
Hi i have an issue with Atom editor. I can't install any packages

![atomerr](https://user-images.githubusercontent.com/48104217/90056317-5764c780-dce7-11ea-8324-ff97453ef0ea.jpg)

C and Python Compiler Tools and Visual Studio 2017 are installed on my system with all compiler packs 

**This is the last log file after i try to update atom or execute apm install --check, apm install, apm update on Command Prompt (Windows 10 Latest Update)**

_*Everything is executed as administrator._

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Users\\whoisfelix\\AppData\\Local\\atom\\app-1.50.0\\resources\\app\\apm\\bin\\node.exe',
> 1 verbose cli   'C:\\Users\\whoisfelix\\AppData\\Local\\atom\\app-1.50.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   '--globalconfig',
> 1 verbose cli   'C:\\Users\\whoisfelix\\.atom\\.apm\\.apmrc',
> 1 verbose cli   '--userconfig',
> 1 verbose cli   'C:\\Users\\whoisfelix\\.atom\\.apmrc',
> 1 verbose cli   'install',
> 1 verbose cli   'https://www.atom.io/api/packages/atom-path-intellisense/versions/1.2.2/tarball',
> 1 verbose cli   '--target=5.0.13',
> 1 verbose cli   '--disturl=https://atom.io/download/electron',
> 1 verbose cli   '--arch=x64',
> 1 verbose cli   '--global-style' ]
> 2 info using npm@6.14.5
> 3 info using node@v10.20.1
> 4 verbose npm-session 7f92f2dc3b4149bc
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 verbose stack Error: spawn C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe ENOENT
> 7 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
> 7 verbose stack     at onErrorNT (internal/child_process.js:415:16)
> 7 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
> 8 verbose cwd C:\Users\WHOISF~1\AppData\Local\Temp\apm-install-dir-2020712-5284-a15le2.w03cv
> 9 verbose Windows_NT 10.0.19041
> 10 verbose argv "C:\\Users\\whoisfelix\\AppData\\Local\\atom\\app-1.50.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\whoisfelix\\AppData\\Local\\atom\\app-1.50.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\whoisfelix\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\whoisfelix\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/atom-path-intellisense/versions/1.2.2/tarball" "--target=5.0.13" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
> 11 verbose node v10.20.1
> 12 verbose npm  v6.14.5
> 13 error code ENOENT
> 14 error syscall spawn C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe
> 15 error path C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe
> 16 error errno ENOENT
> 17 error enoent spawn C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe ENOENT
> 18 error enoent This is related to npm not being able to find a file.
> 19 verbose exit [ 1, true ]

**Comment by 44Armmer** [comment]
> สวัสดี ฉันมีปัญหากับตัวแก้ไข Atom ฉันไม่สามารถติดตั้งแพ็คเกจใด ๆ ได้
> 
> ![อะตอม](https://user-images.githubusercontent.com/48104217/90056317-5764c780-dce7-11ea-8324-ff97453ef0ea.jpg)
> 
> C และ Python Compiler Tools และ Visual Studio 2017 ได้รับการติดตั้งบนระบบของฉันพร้อมกับคอมไพเลอร์แพ็คทั้งหมด
> 
> **นี่เป็นไฟล์บันทึกสุดท้ายหลังจากที่ฉันพยายามอัปเดต atom หรือดำเนินการติดตั้ง apm --check, apm install, apm update บน Command Prompt (อัปเดตล่าสุดของ Windows 10)**
> 
> _*ทุกอย่างดำเนินการในฐานะผู้ดูแลระบบ_
> 
> > 0 ข้อมูลใช้งานได้ถ้ามันลงท้ายด้วย ok 
> > 1 verbose cli [ 'C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe', 
> > 1 verbose cli ' C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\bin\npm-cli.js', 
> > 1 verbose cli '--globalconfig', 
> > 1 verbose cli 'C:\Users\whoisfelix\.atom\.apm\.apmrc', 
> > 1 verbose cli '--userconfig', 
> > 1 verbose cli 'C:\Users\whoisfelix\.atom\.apmrc', 
> > 1 verbose cli 'ติดตั้ง ', 
> > 1 verbose cli 'https://www.atom.io/api/packages/atom-path-intellisense/versions/1.2.2/tarball', 
> > 1 verbose cli '--target=5.0.13', 
> > 1 verbose cli '--disturl=https://atom.io/download/electron',
> > 1 verbose cli '--arch=x64',
> > 1 verbose cli '--global-style' ] 
> > 2 ข้อมูลโดยใช้ npm@6.14.5 
> > 3 ข้อมูลโดยใช้ node@v10.20.1 
> > 4 verbose npm-session 7f92f2dc3b4149bc 
> > 5 โง่ติดตั้ง loadCurrentTree 
> > 6 โง่ติดตั้ง readLocalPackageData 
> > 7 verbose stack ข้อผิดพลาด: วางไข่ C:\ Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe ENOENT 
> > 7 verbose stack ที่ Process.ChildProcess._handle.onexit (ภายใน/child_process.js:240:19) 
> > 7 verbose stack ที่ onErrorNT (internal/child_process.js:415:16) 
> > 7 verbose stack ที่ process._tickCallback (internal/process/next_tick.js:63:19) 
> > 8 verbose cwd C:\Users\WHOISF~1\AppData\ Local\Temp\apm-install-dir-2020712-5284-a15le2.w03cv 
> > 9 ละเอียด Windows_NT 10.0.19041
> > 10 verbose argv "C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe" "C:\Users\whoisfelix\AppData\Local\atom\app" -1.50.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\whoisfelix\.atom\.apm\.apmrc" "--userconfig" "C:\Users\whoisfelix\.atom\.apmrc" "ติดตั้ง" " https://www.atom.io/api/packages/atom-path-intellisense/versions/1.2.2/tarball " "--target =5.0.13" "--disturl= https://atom.io/download/electron " "--arch=x64" "--global-style" 
> > 11 verbose node v10.20.1 
> > 12 verbose npm v6.14.5 
> > 13 ข้อผิดพลาด รหัส ENOENT 
> > 14 เกิดข้อผิดพลาด syscall วางไข่ C:\Users\whoisfelix\AppData\Local\atom\app-1.500\resources\app\apm\bin\node.exe
> > เส้นทางข้อผิดพลาด 15 C:\Users\whoisfelix\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe 
> > 16 ข้อผิดพลาด errno ENOENT 
> > 17 ข้อผิดพลาด enoent วางไข่ C:\Users\whoisfelix\AppData\ Local\atom\app-1.50.0\resources\app\apm\bin\node.exe ENOENT 
> > 18 ข้อผิดพลาด enoent สิ่งนี้เกี่ยวข้องกับ npm ที่ไม่พบไฟล์ 
> > 19 verbose exit [ 1, จริง ]
