### ISSUE TITLE
Uncaught Error: Tried to unload active package 'travis-ci-status'

### ISSUE THREAD

**Issue by dangkhoasdc** [atom/settings-view#300]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0

### Stack Trace

Uncaught Error: Tried to unload active package 'travis-ci-status'

```
At c:\Users\Administrator.AXTNWUDEHRG8MUO\AppData\Local\atom\app-0.165.0\resources\app\src\package-manager.js:364

Error: Tried to unload active package 'travis-ci-status'
  at PackageManager.module.exports.PackageManager.unloadPackage (c:\Users\Administrator.AXTNWUDEHRG8MUO\AppData\Local\atom\app-0.165.0\resources\app\src\package-manager.js:364:15)
  at c:\Users\Administrator.AXTNWUDEHRG8MUO\AppData\Local\atom\app-0.165.0\resources\app\node_modules\settings-view\lib\package-manager.js:269:29
  at exit (c:\Users\Administrator.AXTNWUDEHRG8MUO\AppData\Local\atom\app-0.165.0\resources\app\node_modules\settings-view\lib\package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (c:\Users\Administrator.AXTNWUDEHRG8MUO\AppData\Local\atom\app-0.165.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (c:\Users\Administrator.AXTNWUDEHRG8MUO\AppData\Local\atom\app-0.165.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -2:23.9 settings-view:install-themes (input.hidden-input)
     -1:29.8 core:confirm (input.hidden-input)
  2x -1:26.4 core:move-down (div.settings-view.pane-item)
     -0:16.7 settings-view:install-packages (input.hidden-input)
  5x -0:00.0 core:backspace (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by jlord** [comment]
Have you had any problems like this again?
