### ISSUE TITLE
Uncaught Error: Could not resolve 'markdown-stream' to a package path

### ISSUE THREAD

**Issue by laurelnaiad** [atom/settings-view#303]
I don't know whether there is a trick to reproducing or not, for me it was simply to try to use atom today. As in:

1. Launch atom, then wait...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0

### Stack Trace

Uncaught Error: Could not resolve 'markdown-stream' to a package path

```
At /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:347

Error: Could not resolve 'markdown-stream' to a package path
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:347:15)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:409:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:295:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:582:13
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:690:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:564:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:190:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:156:28)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:201:26
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1143:17

```

### Commands

```
     -0:00.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
```

### Config

```
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
auto-update-packages, v0.2.2
css-color-highlighting, v0.2.4
cucumber, v0.4.0
docblockr, v0.5.8
file-types, v0.3.0
language-xquery, v0.0.1
linter, v0.9.0
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-scss-lint, v0.0.11
minimap, v3.4.9
minimap-color-highlight, v3.0.4
minimap-find-and-replace, v3.0.4
monokai, v0.9.0
recent-files, v0.3.0
syntax-settings, v0.7.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by laurelnaiad** [comment]
To be clearer, the same error began just in my normal atom view. It was when I went into settings to see about fixing it that this particular version of the error came up and offered me the option to report it...
