### ISSUE TITLE
Uncaught TypeError: Cannot read property 'context-menu' of undefined

### ISSUE THREAD

**Issue by robinsound** [atom/settings-view#310]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0

### Stack Trace

Uncaught TypeError: Cannot read property 'context-menu' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:295

TypeError: Cannot read property 'context-menu' of undefined
  at Package.module.exports.Package.activateResources (/Applications/Atom.app/Contents/Resources/app/src/package.js:295:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:207:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:157:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:205:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:410:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)

```

### Commands

```
     -30:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
bootstrap-3-snippetset, v0.0.6
color-picker, v1.2.6
git-diff-details, v0.5.0
go-to-view, v0.1.2
linter, v0.9.1
related-files, v0.3.0
terminal-panel, v1.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
Were you installing a package when this happened? If so, which one?
