### ISSUE TITLE
Uncaught ReferenceError: ErrorView is not defined

### ISSUE THREAD

**Issue by stramel** [atom/settings-view#312]
**OS:** Ubuntu 14.04
**Atom:** 0.167.0-97e0ddf
**settings-view:** 0.163.0

When updating packages it threw an error and the create issue button did not work. Still wanted to get you this information. 

BTW, the new Settings View looks amazing! Thanks for the hard work!

```bash
/usr/local/share/atom/resources/app/node_modules/settings-view/lib/updates-panel.js:79
```

```bash
# Stack Trace
ReferenceError: ErrorView is not defined
  at /usr/local/share/atom/resources/app/node_modules/settings-view/lib/updates-panel.js:79:48
  at /usr/local/share/atom/resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/usr/local/share/atom/resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:368:19)
  at /usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:242:19
  at exit (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/local/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/local/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/local/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)
```

**Comment by kevinsawicki** [comment]
Thanks for reporting this so quickly, it was great to catch this before this was released.

**Comment by stramel** [comment]
@kevinsawicki No problem, I appreciate the hard work!
