### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lweingart** [atom/settings-view#316]
[Enter steps to reproduce below:]

1. Open settings
2. Select Packages
3: Boom

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-packages-panel.js:168

TypeError: undefined is not a function
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.loadPackages (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-packages-panel.js:168:34)
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-packages-panel.js:140:19)
  at InstalledPackagesPanel.View (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new InstalledPackagesPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-packages-panel.js:22:59)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:157:18
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:288:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:324:24)
  at HTMLAnchorElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:141:24)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:12.4 settings-view:open (atom-pane.pane.active)
     -0:00.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
go-format, v1.0.7
go-plus, v3.0.13
linter-javac, v0.1.2
monokai, v0.9.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by lweingart** [comment]
I quit and relaunched, the problem was gone...

**Comment by lweingart** [comment]
oops, didn't see the version was already 0.168
