### ISSUE TITLE
Uncaught TypeError: Cannot read property 'serialize' of undefined

### ISSUE THREAD

**Issue by PoopFeast6969** [atom/settings-view#346]
[Enter steps to reproduce below:]

1. Attempt to install atom-css-comb from package pane in settings.

**Atom Version**: 0.174.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.173.0

### Stack Trace

Uncaught TypeError: Cannot read property 'serialize' of undefined

```
At /Users/Jack/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:485

TypeError: Cannot read property 'serialize' of undefined
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Users/Jack/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:485:32)
  at PackageManager.module.exports.PackageManager.install (/Users/Jack/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:257:23)
  at AvailablePackageView.module.exports.AvailablePackageView.install (/Users/Jack/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/available-package-view.js:323:34)
  at HTMLButtonElement.<anonymous> (/Users/Jack/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/available-package-view.js:162:24)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/Jack/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLButtonElement.elemData.handle (/Users/Jack/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
  4x -9:59.5 core:backspace (atom-text-editor.editor)
     -9:54.5 core:save (atom-text-editor.editor)
     -8:32.3 core:move-right (atom-text-editor.editor)
  2x -8:32.0 core:backspace (atom-text-editor.editor)
     -8:29.4 core:save (atom-text-editor.editor)
  4x -5:43.3 core:backspace (atom-text-editor.editor)
     -5:08.5 core:save (atom-text-editor.editor)
     -4:37.1 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-light-ui)
     -3:07.3 css-comb:comb (atom-text-editor.editor)
     -2:25.5 settings-view:open (atom-text-editor.editor)
  3x -0:00.0 core:backspace (atom-text-editor#atom-beautify.html_indent_size.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-css-comb, v0.6.0
color-picker, v1.3.0
linter, v0.10.0
linter-csslint, v0.0.11

# Dev
No dev packages
```

/cc @atom/core

**Comment by jlord** [comment]
Heya—have you seen this happen recently on a newer version of Atom?

**Comment by Mausy5043** [comment]
Just happened to me when trying to update "Atom Beautify" extension.

FWIW, stack trace:
```
TypeError: Cannot read property 'serialize' of undefined
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Users/maurice/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:465:32)
  at PackageManager.module.exports.PackageManager.update (/Users/maurice/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:273:23)
  at PackageUpdateView.module.exports.PackageUpdateView.upgrade (/Users/maurice/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-update-view.js:175:34)
  at HTMLButtonElement.<anonymous> (/Users/maurice/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-update-view.js:78:24)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/maurice/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Users/maurice/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by mnquintana** [comment]
@Mausy5043 What version of Atom were you on?

**Comment by Mausy5043** [comment]
I'm on OSX Atom v 0.200.0.
It says it's the latest version.

**Comment by jlord** [comment]
@Mausy5043 Do you know which version of `atom-beautify` you had _before_ upgrading to `v0.27.4`?

I just tried with latest Atom, OSX, and picking a random outdated `atom-beautify`, `v0.22.5`, and upgraded to `v0.27.4` without an error.

**Comment by Mausy5043** [comment]
I had `v0.27.3`.

**Comment by arjun-u** [comment]
Happened while updating Atom-Beautify from 0.27.12 to 0.28.0 

Atom Version: 0.207.0
System: Windows 7 SP1

<pre>
TypeError: Cannot read property 'serialize' of undefined
    at PackageManager.module.exports.PackageManager.deactivatePackage (C:\Users\arjun.RZT\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package-manager.js:482:32)
    at PackageManager.module.exports.PackageManager.update (C:\Users\arjun.RZT\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:288:23)
    at PackageUpdateView.module.exports.PackageUpdateView.upgrade (C:\Users\arjun.RZT\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-update-view.js:174:34)
    at HTMLButtonElement.<anonymous> (C:\Users\arjun.RZT\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-update-view.js:78:24)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\arjun.RZT\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\arjun.RZT\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
</pre>

**Comment by johnrizzo1** [comment]
Any update on this.  It is still happening in Atom 1.19.0 with atom-tsd 0.9.0

**Comment by Ben3eeE** [comment]
@johnrizzo1 This issue has already been fixed. If you still see exception this please open a new issue. Please also include steps to reproduce and the full stack trace.
