### ISSUE TITLE
Uncaught TypeError: callback provided to sync glob

### ISSUE THREAD

**Issue by pandemicsyn** [atom/settings-view#365]
[Enter steps to reproduce below:]

1. Open something.go
2. Make any change
3. Hit cmd+s
4. Do what exception warning tells you and submit this issue ;)

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught TypeError: callback provided to sync glob

```
At /Users/fhines/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:67

TypeError: callback provided to sync glob
  at glob (/Users/fhines/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:67:13)
  at /Users/fhines/.atom/packages/go-plus/lib/gobuild.coffee:123:11
  at exit (/Users/fhines/.atom/packages/go-plus/lib/executor.coffee:63:7)
  at BufferedProcess.triggerExitCallback (/Users/fhines/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Users/fhines/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1068:12)

```

### Commands

```
  3x -1:52.9 core:backspace (atom-text-editor.editor.mini)
     -0:23.5 recent-files:0 (atom-text-editor.editor.vim-mode.command-mode)
     -0:11.3 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10.6 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:09.6 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 20x -0:04.3 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.8 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "spacegray-dark-ui",
      "flat2"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.10
file-icons, v1.4.8
flat2, v0.0.0
go-plus, v3.1.2
recent-files, v0.3.0
spacegray-dark-ui, v0.5.0
travis-ci-status, v0.11.2
vim-mode, v0.30.0
web-view, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
I believe this is a `go-plus` package issue, https://github.com/joefitzgerald/go-plus/issues/96

If you upgrade to the latest `go-plus` package version, it should be resolved.
