### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by igmarin** [atom/settings-view#366]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:4:199)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:13:5
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:277:5)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:525:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/general-panel.js:8:19)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/general-panel.js:42:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:22:18)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:370:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at createSettingsView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:12:22)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:39:18
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:568:16)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:418:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at EventEmitter.emit (events.js:119:17)

```

### Commands

```
     -0:05.3 window:install-shell-commands (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.22.1
color-picker, v1.2.6
elixir-cmd, v0.2.3
language-coffee-script, v0.39.0
language-css, v0.26.0
language-elixir, v0.3.3
language-python, v0.29.0
language-ruby, v0.47.0
language-ruby-on-rails, v0.18.0
language-xml, v0.26.0
linter, v0.9.1
linter-elixirc, v0.2.1
monokai, v0.9.0
script, v2.16.0
travis-ci-status, v0.11.1
update-package-dependencies, v0.7.0
vim-mode, v0.24.0
visual-bell, v0.9.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
Does this happen consistently?

**Comment by jlord** [comment]
This looks like a `atom-space-pen-views` error that has since been fixed. Please comment if it happens again on Atom 0.194.0+.
