### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/fs-plus/lib/fs-plus.js'

### ISSUE THREAD

**Issue by howethomas** [atom/settings-view#376]
[Enter steps to reproduce below:]

1. Restarted Atom
2. Opened settings view
3. Bam.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/fs-plus/lib/fs-plus.js'

```
At fs.js:455

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/fs-plus/lib/fs-plus.js'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:313:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.Module._extensions..js (module.js:485:20)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:4:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:252:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:20:12)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:370:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at createSettingsView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:12:22)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:39:18
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:568:16)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:418:19)
  at openPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:18:27)
  at atom-workspace.atom.commands.add.settings-view:install-packages-and-themes (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:55:18)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -0:18.7 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-atom-dark-ui)
     -0:18.5 core:close (atom-text-editor.editor)
     -0:00.5 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "glist"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.12
build, v0.15.0
script, v2.15.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
Does this occur every time you try and open it?

**Comment by jlord** [comment]
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.
