### ISSUE TITLE
Uncaught InvalidCharacterError

### ISSUE THREAD

**Issue by smlombardi** [atom/settings-view#379]
[Enter steps to reproduce below:]

1. Switched theme from Isotope to One Dark

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.178.0

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'remove' on 'DOMTokenList': The token provided ('theme-Oceanic Next') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:464

Error: Failed to execute 'remove' on 'DOMTokenList': The token provided ('theme-Oceanic Next') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at ThemeManager.module.exports.ThemeManager.removeActiveThemeClasses (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:464:36)
  at ThemeManager.module.exports.ThemeManager.deactivateThemes (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:434:12)
  at /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:405:17
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:623:16
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:640:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:804:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:617:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:231:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/themes-panel.js:377:28)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/themes-panel.js:384:24

```

### Commands

```
     -0:45.8 project-manager:toggle (atom-text-editor.editor)
     -0:31.5 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "linter-less",
      "linter-php",
      "linter-csslint"
    ],
    "themes": [
      "one-dark-ui",
      "Oceanic Next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Oceanic Next, v0.0.0
atom-color-highlight, v3.0.8
autocomplete-plus, v2.1.6
color-picker, v1.4.4
emmet, v2.3.3
file-icons, v1.4.10
isotope-ui, v1.3.1
linter, v0.11.1
linter-jshint, v0.1.0
preview-tabs, v0.1.6
project-manager, v1.15.5
project-palette-finder, v2.4.15

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
You have a package `Oceanic Next` that contains a space (looks like you're developing this?).  Atom packages cannot contain spaces.

**Comment by smlombardi** [comment]
Yes, I found and repaired it.  Thanks.
