### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by joshdcomp** [atom/settings-view#381]
[Enter steps to reproduce below:]

1. Open preferences
2. Scroll down to installed packages and click on one
3. Observe the error

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.84.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/joshdcomp/.atom/packages/settings-view/lib/package-snippets-view.coffee:25

TypeError: Cannot read property 'length' of undefined
  at PackageSnippetsView.module.exports.PackageSnippetsView.getSnippetProperties (/Users/joshdcomp/.atom/packages/settings-view/lib/package-snippets-view.coffee:25:5)
  at PackageSnippetsView.module.exports.PackageSnippetsView.getSnippets (/Users/joshdcomp/.atom/packages/settings-view/lib/package-snippets-view.coffee:39:19)
  at PackageSnippetsView.module.exports.PackageSnippetsView.addSnippets (/Users/joshdcomp/.atom/packages/settings-view/lib/package-snippets-view.coffee:47:6)
  at PackageSnippetsView.module.exports.PackageSnippetsView.initialize (/Users/joshdcomp/.atom/packages/settings-view/lib/package-snippets-view.coffee:21:6)
  at PackageSnippetsView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
  at new PackageSnippetsView (/Users/joshdcomp/.atom/packages/settings-view/lib/package-snippets-view.coffee:7:3)
  at InstalledPackageView.module.exports.InstalledPackageView.populate (/Users/joshdcomp/.atom/packages/settings-view/lib/installed-package-view.coffee:70:26)
  at InstalledPackageView.module.exports.InstalledPackageView.initialize (/Users/joshdcomp/.atom/packages/settings-view/lib/installed-package-view.coffee:45:6)
  at InstalledPackageView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
  at new InstalledPackageView (/Users/joshdcomp/.atom/packages/settings-view/lib/installed-package-view.coffee:17:3)
  at /Users/joshdcomp/.atom/packages/settings-view/lib/settings-view.coffee:118:11
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Users/joshdcomp/.atom/packages/settings-view/lib/settings-view.coffee:130:17)
  at SettingsView.module.exports.SettingsView.showPanel (/Users/joshdcomp/.atom/packages/settings-view/lib/settings-view.coffee:141:17)
  at HTMLAnchorElement.<anonymous> (/Users/joshdcomp/.atom/packages/settings-view/lib/settings-view.coffee:61:8)
  at HTMLAnchorElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:08.2 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/Applications/MAMP/htdocs/projects/peasant-balls",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".sass-cache"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.2.0
autocomplete-plus, v0.7.0
block-travel, v0.9.0
char-count, v1.0.0
command-logger, v0.15.0
cucumber, v0.4.0
line-jumper, v0.13.0
linter, v0.7.3
linter-php, v0.0.11
pretty-json, v0.2.0
settings-view, v0.84.0
solarized-dark-syntax, v0.14.0
styleguide, v0.26.0
wrap-guide, v0.16.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
It looks like you have manually installed the `settings-view` package to `/Users/joshdcomp/.atom/packages/settings-view`

If you delete `/Users/joshdcomp/.atom/packages/settings-view` and restart Atom, the bundled version of the `settings-view` package will be used which shouldn't contain this bug.
