### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/nicklas/.atom/packages/go-plus/lib/gocode.coffee'

### ISSUE THREAD

**Issue by tjabodog** [atom/settings-view#389]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/nicklas/.atom/packages/go-plus/lib/gocode.coffee'

```
At /opt/atom/resources/app/src/package.js:240

Error: ENOENT, no such file or directory '/home/nicklas/.atom/packages/go-plus/lib/gocode.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/opt/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:313:15)
  at Object.fs.readFileSync (/opt/atom/resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/opt/atom/resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:194:14)
  at getSourceMap (/opt/atom/resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:302:22)
  at getSourceMapping (/opt/atom/resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:310:19)
  at formatSourcePosition (/opt/atom/resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:262:16)
  at /opt/atom/resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:328:34
  at Function.Error.prepareStackTrace (/opt/atom/resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:331:7)
  at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:240:79)
  at /opt/atom/resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/opt/atom/resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:461:21)
  at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:63:47)
  at /opt/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -3:06.4 core:move-right (atom-text-editor.editor)
  2x -3:05.9 core:select-down (atom-text-editor.editor)
     -3:05.0 core:backspace (atom-text-editor.editor)
     -3:03.7 core:save (atom-text-editor.editor)
     -0:24.2 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-gocode, v0.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This seems similar enough to #388 that I'm going to close this as a duplicate.
