### ISSUE TITLE
Uncaught Error: 'colors.less' wasn't found

### ISSUE THREAD

**Issue by stevenventimiglia** [atom/settings-view#397]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught Error: 'colors.less' wasn't found

```
At /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:380

Error: 
  at new Parser (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:241:16)
  at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:272:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/src/less-compile-cache.js:46:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:363:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:341:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:428:45
  at Array.map (native)
  at ThemePackage.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app/src/package.js:427:59)
  at /Applications/Atom.app/Contents/Resources/app/src/theme-package.js:55:17
  at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app/src/theme-package.js:53:12)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -6:24.9 core:confirm (atom-text-editor.editor.mini)
     -3:54.3 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:39.2 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "merge-conflicts"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.3.0
linter, v0.10.0
minimap, v3.5.6
monokai, v0.12.0
travis-ci-status, v0.11.1
vim-mode, v0.29.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
@stevenventimiglia Can you try upgrading to the [latest version](https://github.com/atom/atom/releases/latest) and see if you can still reproduce this?

**Comment by izuzak** [comment]
If you can still reproduce this in the latest version of Atom with all those packages updated -- please let us know.
