### ISSUE TITLE
Uncaught Error: Unrecognised input

### ISSUE THREAD

**Issue by dimitrioschr** [atom/settings-view#411]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: Unrecognised input

```
At /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:380

Error
  at new Parser (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
  at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/src/less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:363:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:341:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:430:45
  at Array.map (native)
  at ThemePackage.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app/src/package.js:429:59)
  at /Applications/Atom.app/Contents/Resources/app/src/theme-package.js:55:17
  at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app/src/theme-package.js:53:12)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:412:50
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:623:16
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:640:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:804:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:617:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:231:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/themes-panel.js:377:28)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/themes-panel.js:384:24

```

### Commands

```
     -0:11.2 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pylama",
      "file-type-icons",
      "envygeeks-file-icons",
      "file-icon-supplement",
      "atom-lint",
      "simple-flake8",
      "linter-pep8",
      "linter-pyflakes",
      "linter-pylint",
      "linter-python-pyflakes"
    ],
    "themes": [
      "one-dark-ui",
      "pencil-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.1
color-picker, v1.4.4
file-icons, v1.5.1
flake8, v0.6.0
linter, v0.12.0
linter-flake8, v1.3.0
minimap, v4.5.0
script, v2.18.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
This seems to be a problem with the https://github.com/mattly/atom-colors-pencil-dark theme. I just tried to activate it and it threw an exception for me as well. Specifically, this line:

https://github.com/mattly/atom-colors-pencil-dark/blob/cd2b01f2164b513bc38adf1c1291bcb8cd6f044d/index.less#L108

You might consider opening an issue on the theme's repository, but notice that the author mentions in the README that the theme is deprecated:

https://github.com/mattly/atom-colors-pencil-dark
