### ISSUE TITLE
Failed to activate the autocomplete-plus package

### ISSUE THREAD

**Issue by shd101wyy** [atom/settings-view#414]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the autocomplete-plus package

```
At Cannot read property 'bind' of undefined

TypeError: Cannot read property 'bind' of undefined
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:363:117)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "markdown-preview",
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.3
autocomplete-plus, v2.4.1
coffee-compile, v0.11.0
docblockr, v0.6.3
language-latex, v0.4.1
language-lisp, v0.1.1
language-scheme, v1.3.0
linter, v0.12.0
linter-jshint, v0.1.0
markdown-preview-plus, v1.3.0
mathjax-wrapper, v0.1.0
monokai, v0.12.0
texlicious, v0.3.9

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
nvm, I think that is because of the package conflict...

**Comment by donnut** [comment]
What conflict exactly? I'm using io.js v1.5.0 through nvm.
Having the same issue on linux, with atom 0.187

**Comment by jbecwar** [comment]
I'm having the issue on mac osx with 0.187 too.

**Comment by martyphee** [comment]
Me too.

**Comment by mathiasvr** [comment]
Restarting Atom solved this for me. The old version was for some reason still cached in PackageManager.loadedPackages, maybe PackageManager.unloadPackage() was not called during update?
