### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by MehmetNUK** [atom/settings-view#417]
[Enter steps to reproduce below:]

1. search for beautify on install packages screen
2. click on install button on "atom-beautify" package

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:472

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:472:13)
  at PackageGrammarsView.module.exports.PackageGrammarsView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-grammars-view.js:37:31)
  at PackageGrammarsView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageGrammarsView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-grammars-view.js:20:56)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:189:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:177:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:143:12)
  at PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:323:24)
  at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.1
linter, v0.12.0

# Dev
No dev packages
```

**Comment by MarkusMeskanen** [comment]
Happens on any package for me

**Comment by izuzak** [comment]
I'm having trouble reproducing this. @jlord do you have any :bulb: about when/why this might happen?

@MarkusMeskanen Which version of Atom are you using? @MehmetNUK Are you able to reliably reproduce the problem? Is this happening for all packages for you as well or for some packages only?

**Comment by MehmetNUK** [comment]
I can't reproduce the problem because atom-beautify is actually installed although getting this exception message. It happened just for atom-beautify. Other installed packages is listed at the end of my first  comment. There were no problems with it.

**Comment by arnaud512** [comment]
Same here.
Just after installing emmet, in the install packages page, when I click on settings button.

But after the app restart, in the Install section (and Packages section) the settings button works.

I tried to uninstall emmet and reinstall, and no error this time.

![atom](https://cloud.githubusercontent.com/assets/3939593/6676596/76f6064c-cc29-11e4-94fa-fe731624ddd1.png)

---------------------------------------------------

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:472

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:472:13)
  at PackageGrammarsView.module.exports.PackageGrammarsView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-grammars-view.js:37:31)
  at PackageGrammarsView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageGrammarsView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-grammars-view.js:20:56)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:189:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:177:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:143:12)
  at PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:323:24)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:181:26)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
  5x -2:33.5 core:backspace (atom-text-editor.editor.mini)
     -2:30.1 core:copy (atom-text-editor.editor.mini)
     -2:28.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store"
    ],
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "unity-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.4
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by mysticatea** [comment]
+1

I just installed and clicked the setting button.

Windows 7 64bit

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:201

TypeError: Arguments to path.join must be strings
  at f (path.js:201:13)
  at Object.filter (native)
  at Object.win32.join (path.js:206:38)
  at PackageGrammarsView.module.exports.PackageGrammarsView.initialize (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-grammars-view.js:37:31)
  at PackageGrammarsView.View (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageGrammarsView (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-grammars-view.js:20:56)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:189:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:177:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:143:12)
  at PackageDetailView.View (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageDetailView (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:38:54)
  at C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\settings-view.js:323:24)
  at HTMLButtonElement.<anonymous> (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-card.js:181:26)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (C:\Users\t-nagashima.AD\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -9:53.6 core:confirm (atom-text-editor.editor.mini)
  5x -9:43.2 core:backspace (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
linter, v0.12.0
minimap, v4.6.0

# Dev
No dev packages
```

**Comment by wsykurski** [comment]
Hello,
I get  this error to - but only, when starting Atom from GUI (checked on Gnom, Unity, I3). But when starting directly from terminal - like "$ atom &" - everything work fine. Maybe its something with Env. variables ?

**Comment by kevinrobayna** [comment]
same here 
```
path.js:472
Hide Stack Trace
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:472:13)
  at PackageGrammarsView.module.exports.PackageGrammarsView.initialize (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-grammars-view.js:37:31)
  at PackageGrammarsView.View (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageGrammarsView (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-grammars-view.js:20:56)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:191:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:179:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:145:12)
  at PackageDetailView.View (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:323:24)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:181:26)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)
```

Atom version: 0.188.0 24/3/2015 23:05:58

Packages insalled: markdown-pdf

Linux version 3.19.1-201.fc21.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC) ) #1 SMP Wed Mar 18 04:29:24 UTC 2015

``` json
"*":
  "exception-reporting":
    userId: "48c40557-2967-f5ba-7d4f-b58c6ca1e520"
  welcome:
    showOnStartup: false
  core:
    themes: [
      "one-dark-ui"
      "base16-tomorrow-dark-theme"
    ]
  editor:
    invisibles: {}
    fontFamily: "Source Code Pro"
    fontSize: 14
    showInvisibles: true
  "markdown-preview": {}
```

**Comment by mdread** [comment]
same here

**Atom Version**: 0.192.0
**System**: Windows 8.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.192.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:178

TypeError: Arguments to path.join must be strings
  at f (path.js:178:13)
  at Object.filter (native)
  at Object.win32.join (path.js:183:38)
  at PackageGrammarsView.module.exports.PackageGrammarsView.initialize (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\package-grammars-view.js:37:31)
  at PackageGrammarsView.View (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageGrammarsView (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\package-grammars-view.js:20:56)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:199:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:186:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:146:12)
  at PackageDetailView.View (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageDetailView (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\package-detail-view.js:38:54)
  at C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\settings-view.js:323:24)
  at space-pen-div.<anonymous> (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\settings-view\lib\package-card.js:175:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-div.elemData.handle (C:\Users\Daniel\AppData\Local\atom\app-0.192.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Installed Packages

```coffee
# User
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by xoorath** [comment]
1. Settings > Install > merge-conflicts
2. Settings > Install > minimap

Installed both one after the other.

**Atom Version**: 0.194.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.195.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:178

TypeError: Arguments to path.join must be strings
  at f (path.js:178:13)
  at Object.filter (native)
  at Object.win32.join (path.js:183:38)
  at PackageGrammarsView.module.exports.PackageGrammarsView.initialize (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\package-grammars-view.js:37:31)
  at PackageGrammarsView.View (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageGrammarsView (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\package-grammars-view.js:20:56)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:199:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:186:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:146:12)
  at PackageDetailView.View (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new PackageDetailView (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:38:54)
  at C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:323:24)
  at space-pen-div.<anonymous> (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:175:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-div.elemData.handle (C:\Users\xoorath\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
  2x -2:24 core:backspace (div.settings-view.pane-item)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
minimap, v4.7.6

# Dev
No dev packages
```
