### ISSUE TITLE
Failed to load the ide-haskell package

### ISSUE THREAD

**Issue by josgraham** [atom/settings-view#418]
Steps to reproduce:

1. install Atom 0.187
2. install Haskell IDE 0.3.5

Expected Result:
plugin installs without issues

Actual Result:
error message: 'tooltips.less' wasn't found

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to load the ide-haskell package

```
At 'tooltips.less' wasn't found

Error
  at new Parser (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
  at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/src/less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:368:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:346:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:436:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app/src/package.js:435:59)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:186:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -2:01.9 core:backspace (atom-text-editor.editor.mini)
  3x -2:00.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-log, v0.3.0
haskell-ghc-mod, v0.4.3
ide-haskell, v0.3.5
language-haskell, v1.0.0
linter, v0.12.0
linter-clojure, v0.0.4
linter-hlint, v0.3.1
minimap, v4.5.0
monokai, v0.12.0
tasks, v1.3.0
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by izuzak** [comment]
There's a few aspects to this:

1. you're using the unity-ui theme. As far as I can tell, that theme has a `tooltip.less` file, while other themes have a `tooltips.less` file: https://github.com/orderedlist/unity-ui
2. the ide-haskell package is importing "tooltips", which fails if the file doesn't exist: https://github.com/chaika2013/ide-haskell/blob/master/styles/ide-haskell.less

I'm not sure I understand why the package would be importing that "tooltips" file, though. @simurai can you think of a reason for that? I think we can close this and report an issue on the ide-haskell package?

**Comment by simurai** [comment]
It looks like the ide-haskell package uses a [custom tooltip](https://github.com/chaika2013/ide-haskell/blob/75aa4a8519f43a86d84a60a3fbb735960009598f/lib/tooltip-view.coffee] and I guess tries to use some styling from the default tooltips for it.

Yes, I'll close this issue and make a new one in the package.

**Comment by josgraham** [comment]
good catch, thank you!
