### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/request/index.js'

### ISSUE THREAD

**Issue by JustusAdam** [atom/settings-view#419]
1. Updated to version 0.186.0
2. launch

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/request/index.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/request/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at AtomIoClient.module.exports.AtomIoClient.fetchAndCacheAvatar (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:199:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:34:26
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:178:18
  at f (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:129:7)
  at Glob.emit (events.js:116:17)
  at Glob._finish (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:166:8)
  at done (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:155:12)
  at Glob._processReaddir2 (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:346:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:283:17
  at RES (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/inflight/inflight.js:23:14)
  at f (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob._readdirEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:475:10)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:452:12
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.1
ide-haskell, v0.3.5
language-fsharp, v0.8.4
language-haskell, v1.0.0
language-restructuredtext, v0.3.0
language-scala, v1.1.0
minimap, v4.5.0
travis-ci-status, v0.11.2
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by alanhamlett** [comment]
Happens when opening the Preferences menu.

**Comment by JustusAdam** [comment]
Good, I did notice that after installing the (second) update it did not happen again, but I hab already submitted this issue.
