### ISSUE TITLE
Failed to activate the autocomplete-emojis package

### ISSUE THREAD

**Issue by gisu** [atom/settings-view#425]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the autocomplete-emojis package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -1:16.6 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "local-history",
      "grunt-runner",
      "markdown-preview-ghcjs",
      "font-viewer",
      "term2"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
angularjs, v0.1.0
atom-angularjs, v0.1.2
atom-lint, v0.20.1
atom-runner, v2.3.0
autocomplete-emojis, v1.0.0
autocomplete-plus, v2.4.2
bezier-curve-editor, v0.6.6
color-picker, v1.4.4
compass, v0.7.5
dash, v1.0.3
docblockr, v0.6.3
emmet, v2.3.4
file-icons, v1.5.1
language-jade, v0.3.0
linter, v0.12.0
linter-jsl, v0.0.1
linter-php, v0.0.11
linter-scss-lint, v0.0.14
live-archive, v0.1.13
monokai, v0.12.0
project-manager, v1.15.5
terminal-status, v1.3.5
tree-ignore, v0.2.5
wordpress, v0.2.0
wordpress-api, v1.1.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Probably the same than atom/settings-view#416
