### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/opt/atom/resources/app/node_modules/request/index.js'

### ISSUE THREAD

**Issue by cmourouvin** [atom/settings-view#426]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/opt/atom/resources/app/node_modules/request/index.js'

```
At fs.js:574

Error: ENOENT, no such file or directory '/opt/atom/resources/app/node_modules/request/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/opt/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/opt/atom/resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/opt/atom/resources/app/src/babel.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at AtomIoClient.module.exports.AtomIoClient.fetchAndCacheAvatar (/opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:199:21)
  at /opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:34:26
  at /opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:178:18
  at f (/opt/atom/resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob.<anonymous> (/opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:129:7)
  at Glob.emit (events.js:116:17)
  at Glob._finish (/opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:166:8)
  at done (/opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:155:12)
  at Glob._processReaddir2 (/opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:346:12)
  at /opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:283:17
  at RES (/opt/atom/resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/inflight/inflight.js:23:14)
  at f (/opt/atom/resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob._readdirEntries (/opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:475:10)
  at /opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:452:12
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
 49x -1:48.6 core:backspace (atom-text-editor.editor)
     -1:26.0 core:save (atom-text-editor.editor)
     -1:02.4 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -1:02.4 editor:newline (atom-text-editor.editor)
  3x -0:57.6 core:backspace (atom-text-editor.editor)
     -0:49.8 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:49.8 editor:newline (atom-text-editor.editor)
  5x -0:49.5 core:backspace (atom-text-editor.editor)
     -0:47.6 core:save (atom-text-editor.editor)
  2x -0:44.1 core:backspace (atom-text-editor.editor)
     -0:41.0 core:save (atom-text-editor.editor)
     -0:29.6 core:select-all (atom-text-editor.editor)
     -0:26.7 beautify:beautify-editor (atom-text-editor.editor)
     -0:15.1 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:15.1 editor:newline (atom-text-editor.editor)
     -0:12.1 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.4
cucumber, v0.4.1
emmet, v2.3.4
highlight-line, v0.10.1
javascript-snippets, v1.0.0
jshint, v1.3.0
linter, v0.12.0
linter-jshint, v0.1.0

# Dev
No dev packages
```

**Comment by jlord** [comment]
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.
