### ISSUE TITLE
Failed to activate the minimap-git-diff package

### ISSUE THREAD

**Issue by Novashock** [atom/settings-view#427]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the minimap-git-diff package

```
At Cannot read property 'bind' of undefined

TypeError: Cannot read property 'bind' of undefined
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:363:117)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -1:42.7 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -1:42.2 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:50.5 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-plus, v2.4.2
color-picker, v1.4.4
emmet, v2.3.4
highlight-column, v0.4.0
highlight-line, v0.10.1
language-ejs, v0.1.0
linter, v0.12.0
meteor-api, v2.12.0
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
project-manager, v1.15.5
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by abe33** [comment]
Looks like it's related to #416
