### ISSUE TITLE
Failed to activate the minimap-color-highlight package

### ISSUE THREAD

**Issue by stoe** [atom/settings-view#428]
update installed

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the minimap-color-highlight package

```
At Cannot read property 'bind' of undefined

TypeError: Cannot read property 'bind' of undefined
  at Package.module.exports.Package.activateServices (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:363:117)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -3:10.2 core:backspace (atom-text-editor.editor)
     -2:26.0 beautify:beautify-editor (atom-text-editor.editor)
     -2:24.1 snippets:previous-tab-stop (atom-text-editor.editor)
     -2:24.1 editor:outdent-selected-rows (atom-text-editor.editor)
     -2:23.9 snippets:previous-tab-stop (atom-text-editor.editor)
     -2:23.9 editor:outdent-selected-rows (atom-text-editor.editor)
     -2:22.7 beautify:beautify-editor (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-pair"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, vundefined
language-apache, v1.2.0
language-batch, v0.3.2
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-git-diff, v4.1.2
monokai-syntax-for-one-dark, v0.2.1
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by abe33** [comment]
I think this is the same problem than with #416
