### ISSUE TITLE
Failed to activate the ide-haskell package

### ISSUE THREAD

**Issue by saqibsaleem** [atom/settings-view#431]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the ide-haskell package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/Users/saqib/Applications/Atom.app/Contents/Resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/Users/saqib/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Users/saqib/Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Users/saqib/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Users/saqib/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/saqib/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Users/saqib/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Users/saqib/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Users/saqib/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Users/saqib/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Users/saqib/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:41.7 pane:reopen-closed-item (atom-text-editor.editor)
     -0:36.4 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:14.3 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "paredit"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ide-haskell, v0.3.6
language-clojure, v0.13.0
language-groovy, v0.3.0
language-kotlin, v0.2.0
language-scala, v1.1.0
linter-scalac, v0.3.3
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by izuzak** [comment]
This should show up only after you update some packages. If you restart Atom after that everything should be fine. We're tracking this problem over in https://github.com/atom/settings-view/issues/416 so I'm going to close this. Thanks for the report, though!
