### ISSUE TITLE
Failed to load the sublime-default-syntax package

### ISSUE THREAD

**Issue by cristian99garcia** [atom/settings-view#433]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to load the sublime-default-syntax package

```
At 'colors.less' wasn't found

Error
  at new Parser (/opt/atom/resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
  at LessCache.module.exports.LessCache.cssForFile (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/opt/atom/resources/app/src/less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/opt/atom/resources/app/src/theme-manager.js:368:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/opt/atom/resources/app/src/theme-manager.js:346:21)
  at /opt/atom/resources/app/src/package.js:436:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (/opt/atom/resources/app/src/package.js:435:59)
  at /opt/atom/resources/app/src/package.js:186:19
  at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/opt/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:464:30)
  at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:63:47)
  at /opt/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -6:24.5 application:open-file (atom-text-editor.editor)
     -2:18.1 grammar-selector:show (atom-text-editor.editor)
     -2:16.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -2:16.4 core:cancel (atom-text-editor.editor.mini)
  2x -0:42.7 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
minimap, v4.6.0
sublime-default-syntax, v0.1.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Seems like a problem in the sublime-default-syntax package. Try updating Atom and that package to the latest versions and if you can still reproduce -- open an issue over at  https://github.com/Kurtz1993/sublime-syntax/issues.
