### ISSUE TITLE
Uncaught TypeError: Cannot read property 'context-menu' of undefined

### ISSUE THREAD

**Issue by davidsun3000** [atom/settings-view#434]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0
### Stack Trace

Uncaught TypeError: Cannot read property 'context-menu' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:297

TypeError: Cannot read property 'context-menu' of undefined
  at Package.module.exports.Package.activateResources (/Applications/Atom.app/Contents/Resources/app/src/package.js:297:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:209:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:410:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)

```
### Commands

```
     -3:07.9 settings-view:open (input.hidden-input)
     -1:58.3 core:backspace (input.hidden-input)
     -1:40.1 editor:delete-to-beginning-of-line (input.hidden-input)
     -1:34.7 core:backspace (input.hidden-input)
  2x -1:32.4 editor:delete-to-beginning-of-line (input.hidden-input)
  2x -0:00.0 core:confirm (input.hidden-input)
```
### Config

```
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v0.4.0
atom-lint, v0.20.1
autocomplete-plus, v1.1.0
bootstrap-3-snippetset, v0.0.6
jshint, v1.1.3
linter-handlebars, v0.1.1
meteor-api, v2.9.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
No further reports, closing.
