### ISSUE TITLE
Uncaught Error: variable @dark-blue is undefined

### ISSUE THREAD

**Issue by ryanpcmcquen** [atom/settings-view#451]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.187.0

### Stack Trace

Uncaught Error: variable @dark-blue is undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:389

Error
  at new Parser (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
  at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/src/less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:368:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:346:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:442:45
  at Array.map (native)
  at ThemePackage.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app/src/package.js:441:59)
  at /Applications/Atom.app/Contents/Resources/app/src/theme-package.js:55:17
  at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app/src/theme-package.js:53:12)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:11.1 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-plain-theme.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "plain-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
linter-htmlhint, v0.0.12
minimap, v4.7.5
vim-mode, v0.42.0

# Dev
No dev packages
```

**Comment by ryanpcmcquen** [comment]
Issue in my package, fixed here: https://github.com/ryanpcmcquen/atom-plain/commit/235b898f94b4355f18ad660ed6dceb5a749025bc
