### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by chrisesler** [atom/settings-view#454]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.2.0-79-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.185.0

### Stack Trace

Uncaught TypeError: Cannot read property 'sort' of undefined

```
At /usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:169

TypeError: Cannot read property 'sort' of undefined
  at Glob.<anonymous> (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:169:16)
  at Glob.f (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob.emit (events.js:116:17)
  at Glob._readdirError (/usr/share/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:497:36)
  at /usr/share/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js:450:12
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
@chrisesler What were you doing when this error got thrown? I'm trying to reproduce it but I'll need a little more information.
