### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/request/index.js'

### ISSUE THREAD

**Issue by jsenjoy** [atom/settings-view#459]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.185.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/request/index.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/request/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:362:29)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at AtomIoClient.module.exports.AtomIoClient.fetchAndCacheAvatar (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:199:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:34:26
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:178:18
  at f (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:129:7)
  at Glob.emit (events.js:116:17)
  at Glob._finish (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:166:8)
  at done (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:155:12)
  at Glob._processReaddir2 (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:346:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:283:17
  at RES (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/inflight/inflight.js:23:14)
  at f (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob._readdirEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:475:10)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:452:12
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:06.7 settings-view:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "tomorrow-night-eighties"
    ],
    "disabledPackages": [
      "vim-mode",
      "autocomplete-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.0
atom-jade, v0.1.0
dash, v1.0.0
docs-snippets, v0.8.0
emmet, v2.3.0
javascript-snippets, v1.0.0
jshint, v1.1.5
language-ejs, v0.1.0
language-velocity, v0.1.0
pretty-json, v0.3.2
remember-session, v0.5.1
seti-ui, v0.5.1
tomorrow-night-eighties, v0.1.0

# Dev
No dev packages
```

**Comment by jlord** [comment]
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.
