### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getKeyBindings' of undefined

### ISSUE THREAD

**Issue by yasuyuki** [atom/settings-view#460]
**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.187.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getKeyBindings' of undefined

```
At /Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:49

TypeError: Cannot read property 'getKeyBindings' of undefined
  at PackageKeymapView.module.exports.PackageKeymapView.initialize (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:49:26)
  at PackageKeymapView.View (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageKeymapView (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:16:54)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:190:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:179:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:145:12)
  at PackageDetailView.View (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:258:18
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:323:24)
  at space-pen-div.<anonymous> (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Volumes/ssd/y.inoue/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autocomplete-plus, v2.9.0
change-case, v0.5.1
dash, v1.1.0
extract-method, v0.1.0
git-blame, v0.4.0
git-history, v2.3.0
japanese-wrap, v0.2.5
linter, v0.12.0
linter-rubocop, v0.2.2
live-archive, v0.1.13
merge-conflicts, v1.2.10
project-manager, v1.15.5
stacktrace, v0.0.1

# Dev
No dev packages
```

**Comment by andya9** [comment]
I confirm the issue on linux, atom 0.190.0

**Comment by izuzak** [comment]
@andya9 Thanks for helping investigate! 

I see errors thrown when I do any of these actions if running `atom -1` (/cc @kevinsawicki):
* visit the Keybindings section of the Settings View
* visit the view for a specific package in the Packages section of the Settings View

@yasuyuki is this how you triggered the error as well? If not, can you share the steps to reproduce? Also, can you let us know if you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by andya9** [comment]
@izuzak 
For me it is exactly the same as you; works fine both in safe mode and without -1

**Comment by andya9** [comment]
Thank’you @kevinsawicki

**Comment by yasuyuki** [comment]
I met this only once.
I updated Atom to 0.190 and restarted, then it occurred. I tried to restart Atom again, it didn't happen.
It may be a bug of Atom 0.190.

**Comment by mnquintana** [comment]
@yasuyuki This has been fixed for the next release of Atom (0.191.0)

**Comment by kirollosmagdy** [comment]
Hi, i was just in the settings getting some packages installed (emmit, typescript) and then that error keeps popping up!

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.187.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getKeyBindings' of undefined

```
At /Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:49

TypeError: Cannot read property 'getKeyBindings' of undefined
  at PackageKeymapView.module.exports.PackageKeymapView.initialize (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:49:26)
  at PackageKeymapView.View (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageKeymapView (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:16:54)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:190:30)
  at /Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:211:24
  at /Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:368:19)
  at /Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:275:26
  at exit (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Users/kirollosmagdy/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -1:08.1 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
  3x -1:07.3 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.3 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:03.7 pane:show-previous-item (div.settings-view.pane-item)
     -1:03.5 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:03.0 pane:show-previous-item (div.settings-view.pane-item)
     -1:02.8 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:02.4 pane:show-previous-item (div.settings-view.pane-item)
     -1:02.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:01.6 pane:show-previous-item (div.settings-view.pane-item)
  2x -1:00.7 editor:newline (atom-text-editor.editor.is-focused)
 11x -0:56.2 core:undo (atom-text-editor.editor.is-focused)
     -0:51.3 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:46.9 core:select-all (atom-text-editor.editor.mini)
     -0:45.5 core:backspace (atom-text-editor.editor.mini)
     -0:43.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript, v2.14.5
autocomplete-plus, v2.9.0
emmet, v2.3.7
linter, v0.12.0

# Dev
No dev packages
```

**Comment by hayao56** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.187.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getKeyBindings' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:49

TypeError: Cannot read property 'getKeyBindings' of undefined
  at PackageKeymapView.module.exports.PackageKeymapView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:49:26)
  at PackageKeymapView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageKeymapView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-keymap-view.js:16:54)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:190:30)
  at PackageDetailView.module.exports.PackageDetailView.populate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:179:19)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:145:12)
  at PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:258:18
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:323:24)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:181:26)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
  2x -0:23.1 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "recent-files",
      "open-terminal-here",
      "bracket-matcher"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
git-diff, v0.54.0
git-plus, v4.4.13
git-projects, v1.13.0

# Dev
No dev packages
```
