### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#465]
*(Note: Not a duplicate of #359)*

[Enter steps to reproduce below:]

1. Open Settings > Install 
2. Find package that you haven't installed yet
3. Click on package card body

I have also gotten this in safe mode.

**Atom Version**: 0.191.0-a68e837
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.191.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:155

TypeError: undefined is not a function
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:155:26)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:145:12)
  at PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:323:24)
  at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:175:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -0:18.8 settings-view:open (atom-text-editor.editor)
     -0:10.6 core:backspace (atom-text-editor.editor.mini)
     -0:09.7 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-scss-lint",
      "jshint",
      "atom-ungit",
      "sublime-tabs",
      "save-session",
      "script",
      "linter-shellcheck",
      "asciidoc-preview"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-atom-api, v0.7.0
autocomplete-css, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
color-picker, v1.6.0
editorconfig, v0.3.3
file-icons, v1.5.4
git-tab-status, v1.7.0
language-asciidoc, v0.11.1
language-haml, v0.19.0
language-jade, v0.4.0
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-js-yaml, v1.0.0
linter-jscs, v1.10.0
linter-jshint, v0.1.2
linter-rubocop, v0.2.2
minimap, v4.7.6
project-palette-finder, v2.4.16
travis-ci-status, v0.13.0

# Dev
fuzzy-finder, v0.72.0
tabs, v0.67.0
travis-ci-status, v0.13.0
tree-view, v0.170.0
wrap-guide, v0.32.0
```

**Comment by izuzak** [comment]
Probably related to https://github.com/atom/settings-view/pull/371.
