### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/drivard/.atom/packages/autocomplete-plus/lib/provider.coffee'

### ISSUE THREAD

**Issue by donaldrivard** [atom/settings-view#486]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/drivard/.atom/packages/autocomplete-plus/lib/provider.coffee'

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:241

Error: ENOENT, no such file or directory '/Users/drivard/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:194:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:302:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:310:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:262:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:328:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:331:7)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:241:79)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:54.5 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-theme.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "backbonejs-snippets"
    ],
    "themes": [
      "atom-light-ui",
      "dracula-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-backbone, v0.6.0
atom-grunt-configs, v0.1.0
dracula-theme, v0.7.6
grunt-runner, v0.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Please upgrade to the latest Atom version, 0.194.0.  This has been fixed.
