### ISSUE TITLE
Failed to activate the indentation-indicator package

### ISSUE THREAD

**Issue by dasilvacontin** [atom/settings-view#492]
I updated the `Indentation Indicator` package to version 0.5.0.

**Atom Version**: 0.188.0-f57abc9
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.185.0

### Stack Trace

Failed to activate the indentation-indicator package

```
At Cannot read property 'bind' of undefined

TypeError: Cannot read property 'bind' of undefined
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:365:117)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
    at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
```

### Commands

```
     -0:14.2 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
indentation-indicator, v0.5.0
vim-mode, v0.45.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
You're on an old version of Atom. Please update to the latest version and let me know whether this reproduces or not.

**Comment by kevinsawicki** [comment]
This was fixed by https://github.com/atom/atom/pull/6026
