### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar'

### ISSUE THREAD

**Issue by DarkChango** [atom/settings-view#523]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.205.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar'
  at Error (native)
  at fs.openSync (fs.js:544:18)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
  at Object.loadFile [as .js] (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/src/babel.js:138:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at createSettingsView (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:12:22)
  at /Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:43:26
  at wrappedOpener (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:511:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:433:22)
  at Workspace.module.exports.Workspace.open (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:366:19)
  at atom-workspace.atom.commands.add.settings-view:check-for-package-updates (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:74:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at HTMLAnchorElement.atom.notifications.addInfo.buttons.onDidClick (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:109:33)
  at HTMLAnchorElement.<anonymous> (/Users/Chango/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:137:42)

```

### Commands

```
     -0:00.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
@DarkChango does this still happen to you on the latest atom version? Looks like you werent able to open the settings view at all.
