### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by crperlin** [atom/settings-view#536]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.207.0

### Stack Trace

Uncaught TypeError: Cannot read property 'serialize' of undefined

```
At C:\Users\CRPER\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package-manager.js:481

TypeError: Cannot read property 'serialize' of undefined
  at PackageManager.module.exports.PackageManager.deactivatePackage (C:\Users\CRPER\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package-manager.js:481:32)
  at PackageManager.module.exports.PackageManager.update (C:\Users\CRPER\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:288:23)
  at PackageUpdateView.module.exports.PackageUpdateView.upgrade (C:\Users\CRPER\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\settings-view\lib\package-update-view.js:174:34)
  at HTMLButtonElement.<anonymous> (C:\Users\CRPER\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\settings-view\lib\package-update-view.js:78:24)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\CRPER\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\CRPER\AppData\Local\atom\app-0.206.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:58.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:58.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:53.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:49.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45.4.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:45.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:45.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:45.4.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:45.4.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:44.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:44.1.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:44.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:44.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:44.1.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:44.1.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -0:43.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "seti-syntax"
    ],
    "disabledPackages": [],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.10
color-picker, v2.0.4
csslint, v1.1.3
docblockr, v0.7.2
emmet, v2.3.10
file-icons, v1.5.7
jslint, v1.3.3
linter, v0.12.6
linter-csslint, v0.0.13
linter-jshint, v0.1.6
linter-less, v0.5.0
linter-scss-lint, v1.0.4
minimap, v4.9.4
open-in-browser, v0.4.6
seti-syntax, v0.4.0
tree-view-finder, v0.2.1
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by jlord** [comment]
Between `settings-view` versions 207 and 210 the code has changed quite a bit and the `upgrade` method in the stack trace no longer exists. I think we can close for now and see if the issue occurs again with the changes.
