### ISSUE TITLE
Failed to load the linter package

### ISSUE THREAD

**Issue by phagoth** [atom/settings-view#576]
[Enter steps to reproduce below:]

1. Starting Install linter-eslint
2. Before previous intalation ends I'm start updating Linter package

**Atom Version**: 1.0.0
**System**: Linux Mint
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.208.0

### Stack Trace

Failed to load the linter package

```
At EACCES: permission denied, open '/home/alexander/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/content/321db3ac9eb7ba5880171a2f9d21d4d8e6ea9189/linter-plus.json'

Error: EACCES: permission denied, open '/home/alexander/.atom/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/content/321db3ac9eb7ba5880171a2f9d21d4d8e6ea9189/linter-plus.json'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.writeFileSync (fs.js:1155:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
  at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
  at LessCache.module.exports.LessCache.putCachedCss (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:225:19)
  at LessCache.module.exports.LessCache.cssForFile (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:276:12)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/usr/share/atom/resources/app.asar/src/less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:308:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app.asar/src/theme-manager.js:286:21)
  at /usr/share/atom/resources/app.asar/src/package.js:454:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (/usr/share/atom/resources/app.asar/src/package.js:453:59)
  at /usr/share/atom/resources/app.asar/src/package.js:185:19
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:451:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:306:60
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -7:43.5.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:35.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -7:32.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -5:53.9.0 core:save (atom-text-editor.editor.is-focused)
  4x -5:33.1.0 core:undo (atom-text-editor.editor.is-focused)
     -4:41.2.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -0:27.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-ruby"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.2.0
linter-eslint, v1.0.18
linter-rubocop, v0.2.7

# Dev
No dev packages
```

**Comment by benogle** [comment]
cc @kevinsawicki

**Comment by phagoth** [comment]
Probably *permission denied* caused starting Atom not as superuser

**Comment by Arcanemagus** [comment]
Shouldn't this be closed? The issue was a permissions problem on the compile-cache, I'm not even sure how the bug reporter though this was coming from the settings view other than that just happened to be the thing attempting to load the source file (to grab the config object).
