### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by spencerthayer** [atom/settings-view#577]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.1
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
  at ErrorView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ErrorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:156:44
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:359:17
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:384:20
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  2x -0:34.6.0 core:close (div.release-notes.padded.pane-item.native-key-bindings)
     -0:26.6.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:21.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "atom-beautify",
      "jsformat",
      "Tern",
      "Tern"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.3.5
atom-jshint, v2.0.0
atom-minify, v0.1.7
autocomplete-emojis, v2.2.2
autocomplete-hack, v1.0.1
autocomplete-modules, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-phpunit, v1.0.2
autocomplete-python, v0.5.1
color-picker, v2.0.9
css-snippets, v0.8.0
editorconfig, v1.0.1
emmet, v2.3.12
javascript-snippets, v1.0.0
language-javascript-better, v1.5.0
linter, v1.2.0
minimap, v4.11.0
monokai, v0.14.0
node-debugger, v1.1.4
pigments, v0.8.3
selector-to-tag, v0.4.1
sourcegraph-atom, v0.2.2
vim-mode, v0.54.0
wakatime, v4.0.12

# Dev
No dev packages
```

**Comment by nikchosh** [comment]
Same issue today trying to install angular-ui on Atom 1.0.0

**Comment by benogle** [comment]
This was a regression caused by the move from emissary -> event-kit. Event kit only handles one argument passed to `emit`.

This will be out in the next version of atom: 1.0.3.

**Comment by johnnyoshika** [comment]
I'm running into the same problem trying to install the last-cursor-position package.

**Comment by benogle** [comment]
Really sorry about this. It will be out in the next version of atom. 

This only happens when there is an error installing or uninstalling a package. So make sure you have an internet connection and that you can install packages. You might want to install on the command line to uncover the error:

`apm install last-cursor-position` should do the trick.

**Comment by shizhi-li** [comment]
l write python,l will install script.but atom Prompted :Uncaught TypeError: Cannot read property 'message' of undefined. l don't understand.
my computer is Windows 8.1 x64
can you help me?please! Thanks

**Comment by tomalec** [comment]
I got the same message when trying to install Glavin001/atom-beautify, and thedaniel/terminal-panel
`apm install package-name`
results is errors like:
```log
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Users\\tomalec\\AppData\\Local\\atom\\app-1.0.2\\resources\\app\\apm\\bin\\node.exe" "c:\\Users\\tomalec\\AppData\\Local\\atom\\app-1.0.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\tomalec\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\tomalec\\.atom\\.apmrc" "install" "C:\\Users\\tomalec\\AppData\\Local\\Temp\\d-115622-7560-1ddmpmt\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! file C:\Users\tomalec\.atom\.apm\map-stream\0.0.6\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token
npm ERR! File: C:\Users\tomalec\.atom\.apm\map-stream\0.0.6\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

So I manually clean `rm -r .~\.atom\.apm\map-stream`, then it complains about another, and another.. So I need to perform such manual operation many times, to finally get it working.

Related issues: https://github.com/Glavin001/atom-beautify/issues/442, https://github.com/atom/atom-space-pen-views/issues/13
