### ISSUE TITLE
language-babel package does not appear in packages view

### ISSUE THREAD

**Issue by cperryk** [atom/settings-view#588]
When installed, the language-babel package [appears for me only in the "install" view](https://www.dropbox.com/s/da00e6aeun1h33b/Screenshot%202015-07-15%2010.34.50.png?dl=0), not the ["packages" view](https://www.dropbox.com/s/49bin09634x6fo3/Screenshot%202015-07-15%2010.35.34.png?dl=0) (even though it's already installed). I can only access its settings by searching it in the "install" view. Reinstalling the package, whether inside Atom or via `apm`, does not resolve the issue.

[Issue on github/gadm/language-babel](https://github.com/gandm/language-babel/issues/23#issuecomment-121535225)

I am getting this possibly related error in the console whether it's installed or not:

```
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/kirkcp/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at /Users/kirkcp/.atom/packages/task-list/lib/task-list-view.coffee:6:3
  at Object.<anonymous> (/Users/kirkcp/.atom/packages/task-list/lib/task-list-view.coffee:124:5)
  at Object.<anonymous> (/Users/kirkcp/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/kirkcp/.atom/packages/task-list/lib/task-list.coffee:1:16)
  at Object.<anonymous> (/Users/kirkcp/.atom/packages/task-list/lib/task-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:42:14)
  at PackageCard.module.exports.PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:612:34)
  at PackageCard.module.exports.PackageCard.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
  at PackageCard.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.createPackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:324:18)
  at ListView.__bind [as createView] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:3:61)
  at ListView.module.exports.ListView.addView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:50:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:13:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at List.module.exports.List.setItems (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list.js:42:22)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:272:28
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at Promise.then.Q.nextTick.self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)
```

**Comment by cperryk** [comment]
Uninstalling the task-list package resolved this. See kenwheeler/task-list#18
