### ISSUE TITLE
Can't find an installed package in "Packages", have to search it in "Install"

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#591]
_From @DiThi on July 16, 2015 19:13_

![installed_package](https://cloud.githubusercontent.com/assets/1127198/8732680/4d56525c-2bff-11e5-9622-5b3919c56a2d.gif)

I forgot to capture the mouse cursor, but I hope it's clear the package is installed.

_Copied from original issue: atom/atom#7937_

**Comment by mnquintana** [comment]
What version of Atom are you using?

**Comment by mnquintana** [comment]
_From @DiThi on July 16, 2015 19:17_

1.0.2

I don't even know how to disable auto update, something I'd like to do because it caused me problems in the past.

**Comment by gfarrell** [comment]
I am having the same problem on atom 1.0.5, OSX 10.10.4. Many of the packages I have installed don't show up when I search for them and don't always show up in "install" either (from atom/atom#8324).

**Comment by christopherdwhite** [comment]
I'm also having this issue, I have a ton of packages but most of them are disabled while I figure out which ones stick for me. I hadn't tried searching for them in _Install_ but missing packages show up in the command palette, packages menu, Config file and in the [package-list](https://atom.io/packages/package-list).

Please let me know if there's anything I can do to help you track down the issue.

Atom: 1.0.11
OS X:  10.11 Beta (15A279b) - Beta 8

**Comment by christopherdwhite** [comment]
If it helps I'm getting the following errors in the console that may be related to the issue: 
![atom console 1](https://cloud.githubusercontent.com/assets/1746405/9673216/2b676a6a-525f-11e5-8c02-ba33d5c1863b.png)
![atom console 2](https://cloud.githubusercontent.com/assets/1746405/9673241/6159337e-525f-11e5-9968-f2f0c6e0b400.png)

Any chance that Atom doesn't like being outside of /Applications/ ?

**Comment by AgentME** [comment]
I've been having the same problem. I've posted some screenshots [here](https://github.com/atom/atom/issues/8678).

My Packages page says that the "Community Packages" section has 14 items, but only shows 1!

**Comment by peduxe** [comment]
@AgentME It's very likely you have a package not loading, fwiw I think that once a package activation fails, the rest may not load correctly.

Check your console for exceptions.

**Comment by abhisekp** [comment]
I'm using Atom 1.0.11 under Windows 7 x64 SP1
I've 53 community packages installed but the community packages in the settings shows only very few. Lots of other packages are missing. But i'm able to ues them in the editor.

**Comment by AgentME** [comment]
@peduxe Thanks, looks like the `require` package was the cause. Removing it worked around the issue. Here's the full stack trace if it's useful:

```
atom.project.getPath is not a function TypeError: atom.project.getPath is not a function
  at Object.<anonymous> (/Users/chris/.atom/packages/require/views/require-view.js:3:32)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/chris/.atom/packages/require/index.js:2:19)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:42:14)
  at PackageCard.module.exports.PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:611:34)
  at PackageCard.module.exports.PackageCard.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
  at PackageCard.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.createPackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:327:18)
  at ListView.__bind [as createView] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:3:61)
  at ListView.module.exports.ListView.addView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:50:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:13:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at List.module.exports.List.setItems (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list.js:42:22)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:275:28
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)
```

**Comment by Sam2304** [comment]
Same issue as others:
Atom: 1.0.19
Ubuntu Vivid 15.04 x64
Packages list fails to load all packages, error in console as follows:

```
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:1:1)
  at /home/sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:5:3
  at Object.<anonymous> (/home/sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:66:5)
  at Object.<anonymous> (/home/sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/sam/.atom/packages/npm-docs/lib/npm-docs.coffee:5:15)
  at Object.<anonymous> (/home/sam/.atom/packages/npm-docs/lib/npm-docs.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:263:14)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:42:14)
  at PackageCard.module.exports.PackageCard.hasSettings (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:611:34)
  at PackageCard.module.exports.PackageCard.initialize (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
  at PackageCard.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageCard (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.createPackageCard (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:327:18)
  at ListView.createView (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:3:61)
  at ListView.module.exports.ListView.addView (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/list-view.js:50:19)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/list-view.js:13:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at List.module.exports.List.setItems (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/list.js:42:22)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:275:28
  at _fulfilled (/usr/share/atom/resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app.asar/node_modules/q/q.js:756:13)
  at /usr/share/atom/resources/app.asar/node_modules/q/q.js:564:44
  at flush (/usr/share/atom/resources/app.asar/node_modules/q/q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickDomainCallback (node.js:386:13)
(anonymous function) @ /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:288
```

Let me know if there is anything else I can provide.  It doesn't appear to point to any particular package breaking things, I don't have some of the packages mentioned by users above, my issue appears to be npm-docs-view

**Comment by gaurav21r** [comment]
+1

**Comment by joseluiscd** [comment]
It looks like it is a problem with a defective package. In my case, I noticed this issue after installing the [snake](https://atom.io/packages/snake) package (I only wanted to try it). When I uninstalled it, after restarting atom, I got the whole list of packages.

When it wasn't working, I had a log similar to @christopherdwhite and @Sam2304.

**Atom version**: *1.0.19*

**Comment by piotrwitek** [comment]
+1, I think you could easily reproduce this bug with "sync-settings" package:
- install few packages
- just do a backup
- uninstall or just delete entire .atom packages directory
- try to restore a backup with "sync-settings"
They will be reinstalled and visible using apm list command, but some of them will not be seen under atom->settings>packages list

**Comment by juliesunset** [comment]
Hi,
Problem still unsolved since last update. Now using Atom v1.5.4. Maybe a bit different in the way that my package list menu is not showing all my installed package. Still can use some but cannot launch features normally only accessible by the menu. Included print screens. My console doesn't report any error except deprecated elements (/deep/ combinator & shadow pseudo-element).
![error1](https://cloud.githubusercontent.com/assets/17161855/13614472/ad699cf0-e53e-11e5-9ca0-d750ddb3004e.png)
![error2](https://cloud.githubusercontent.com/assets/17161855/13614478/b0448a02-e53e-11e5-9218-60255913db04.png)

**Comment by jpeddicord** [comment]
I think @joseluiscd is correct. I noticed this on Atom 1.6.2 with a development package I was working on. There was an error in my own package (missing module), which seemed to cause Atom's module loader to bail out on loading anything else in the settings view. I could only see a handful of installed packages there. After removing my dev package, everything loaded up fine.

**Comment by iToto** [comment]
FYI I am seeing this on v1.9.9

**Comment by tluge** [comment]
This problem also appears (or persists) in Atom version 1.10.2:

I installed a package that throws errors during installation (zotero-citations ver. 0.19.0). With this package installed, only one of nine community packages was listed in the "packages" section. The broken package dis appear as installed in the "install" section, however. Removing it from there and restarting Atom restores the proper behavior.

**Comment by cfirmi** [comment]
I was having a problem with Atom-live-server not showing in the packages.
My Solution:
You have to rebuild the packages by clicking the "Bug" icon in the bottom right hand corner and reload Atom 
Hopefully this works for some of you
