### ISSUE TITLE
Uncaught TypeError: Cannot read property 'serialize' of undefined

### ISSUE THREAD

**Issue by crperlin** [atom/settings-view#621]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.2

### Stack Trace

Uncaught TypeError: Cannot read property 'serialize' of undefined

```
At C:\Users\WIN7\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:497

TypeError: Cannot read property 'serialize' of undefined
  at PackageManager.module.exports.PackageManager.deactivatePackage (C:\Users\WIN7\AppData\Local\atom\app-1.0.3\resources\app.asar\src\package-manager.js:497:32)
  at PackageManager.module.exports.PackageManager.update (C:\Users\WIN7\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:294:23)
  at PackageCard.module.exports.PackageCard.update (C:\Users\WIN7\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\settings-view\lib\package-card.js:655:34)
  at HTMLButtonElement.<anonymous> (C:\Users\WIN7\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\settings-view\lib\updates-panel.js:71:112)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\WIN7\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\WIN7\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -5:05.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:00.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -5:00.0 core:save (atom-text-editor.editor.is-focused)
  3x -4:38.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:35 core:save (atom-text-editor.editor.is-focused)
  3x -4:31.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:29.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:45.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:44.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:06.3.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -3:04.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:27.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:27.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:27.8.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -1:13.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:11.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.10
atom-html-preview, v0.1.11
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.13
color-picker, v2.0.11
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.6.2
file-type-icons, v0.7.1
js-refactor, v0.4.2
jsformat, v0.9.0
linter, v1.3.1
linter-js-standard, v2.4.0
linter-jshint, v1.1.4
linter-less, v2.0.3
linter-scss-lint, v2.0.0
minimap, v4.12.2
minimap-find-and-replace, v4.2.0
nuclide-diagnostics-ui, v0.0.26
pigments, v0.9.3
symbols-tree-view, v0.9.3
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by Baltasarq** [comment]
Same here. This is an Ubuntu box, and the error was thrown while updating the Atom Beuatifier.

**Comment by sumitpatidar** [comment]
Same here on mac os X

**Comment by lichenhao** [comment]
Same problem on mac os X

**Comment by MoinMoti2310** [comment]
on ubuntu, same error while updating script

**Comment by JohnTian** [comment]
Same problem on Mac book pro OS X.

**Comment by adam-dorin** [comment]
Same here windows 7

**Comment by LeoHughes** [comment]
Same problem on windows 8.1

**Comment by matthewhoendorf** [comment]
+1 on Windows 10

**Comment by JohnTian** [comment]
The current version of my Atom is 1.5.4. And the problem I encounter had gone with some unknown reason.  I guess this maybe under the influence of the GFW.

**Comment by Alvarz** [comment]
Same here on Ubuntu 14.04 lts and atom 1.6.1

**Comment by Westen0x** [comment]
+ 1 Win 10

**Comment by Tautorn** [comment]
Some solution?
Ubuntu 18.04 here
