### ISSUE TITLE
the package is broken after latest update

### ISSUE THREAD

**Issue by corangec** [atom/settings-view#625]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.208.0

### Stack Trace

Uncaught TypeError: Cannot read property 'serialize' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:482

TypeError: Cannot read property 'serialize' of undefined
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:482:32)
  at PackageManager.module.exports.PackageManager.uninstall (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:390:23)
  at PackageCard.module.exports.PackageCard.uninstall (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:669:34)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:284:24)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -9:52.1.0 vim-mode:substitute-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -9:51.1.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -9:42.2.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -9:38.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -9:23.7.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -9:06.9.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -9:06.4.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -9:04.7.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -8:57.9.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -8:50.5.0 atom-beautify:beautify-editor (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:25.7.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -0:38.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
auto-update-packages, v1.0.0
color-picker, v2.0.7
date, v1.0.0
minimap, v4.12.2
pigments, v0.9.3
pretty-json, v0.4.1
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
You're running an extremely old version of Atom - please update to Atom 1.0.5.
