### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeClass' of undefined

### ISSUE THREAD

**Issue by JPomichael** [atom/settings-view#630]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.213.0
### Stack Trace

Uncaught TypeError: Cannot read property 'removeClass' of undefined

```
At C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:195

TypeError: Cannot read property 'removeClass' of undefined
  at PackageDetailView.module.exports.PackageDetailView.showLoadingMessage (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:195:33)
  at PackageDetailView.module.exports.PackageDetailView.fetchPackage (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:179:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:171:23)
  at C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:587:27)
  at C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:378:26
  at exit (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\JPOMICHAEL-WORK\AppData\Local\atom\app-1.0.7\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
  6x -3:04.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:51.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "D:\\Development\\Projects",
    "disabledPackages": [
      "github-issues",
      "open-on-github"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-CHS-menu, v0.0.1
build-markdown, v1.0.2
file-icons, v1.6.3
markdown-format, v2.5.1
markdown-scroll-sync, v0.4.0
minimap, v4.12.3
my-github-profile, v0.2.1
pigments, v0.11.0

# Dev
No dev packages
```

**Comment by kktspecial** [comment]
Does anyone have a fix for this?

**Comment by damieng** [comment]
A lot of this system has been rewritten since this bug was filed - if you are experiencing the same message can you open a new issue with the new stack trace (the one above is very out of date)
