### ISSUE TITLE
Uncaught TypeError: path.extname is not a function

### ISSUE THREAD

**Issue by lee-dohm** [atom/settings-view#652]
[Enter steps to reproduce below:]

1. Start Atom
1. Open the Settings View with <kbd>Cmd+,</kbd>
1. Search for a package that has key bindings
1. Scroll down to the key bindings section
1. Click the <span class="octicon octicon-clippy"></span> icon

**Atom Version**: 1.0.12-ad95281
**System**: Mac OS X 10.10.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught TypeError: path.extname is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-keymap-view.js:147

TypeError: path.extname is not a function
  at PackageKeymapView.module.exports.PackageKeymapView.writeKeyBindingToClipboard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-keymap-view.js:147:30)
  at HTMLSpanElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-keymap-view.js:139:24)
  at space-pen-section.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-section.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:26.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:25.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:24.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:22.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:16.1.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -1:12.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.8.0 core:paste (atom-text-editor.editor.is-focused)
     -1:09.9.0 core:save (atom-text-editor.editor.is-focused)
 10x -1:08.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -1:05.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:58.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:46.7.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
     -0:43.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:43.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:34.8.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:30.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "projectHome": "/Users/Lee/Source",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      ".keep",
      "._*",
      "*.pyc",
      "Thumbs.db"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.9.2
autocomplete-elixir, v1.3.12
autocomplete-emojis, v2.2.2
block-travel, v1.0.2
bug-report, v0.7.1
file-type-icons, v0.7.3
indentation-indicator, v0.6.0
language-asciidoc, v0.12.0
language-elixir, v0.5.2
language-generic-config, v0.2.0
language-haml, v0.21.0
language-todotxt, v0.6.1
minimap, v4.13.3
pigments, v0.14.0
red-wavy-underline, v0.3.0
regex-railroad-diagram, v0.8.4
set-syntax, v0.3.0
soft-wrap-indicator, v0.7.0
tabs-to-spaces, v0.11.1

# Dev
indentation-indicator, v0.6.0
```

**Comment by reecebisel** [comment]
clicked packages under settings, went to change keybinding for autocomplete-plus, received error linking me here. In essence my auto complete isn't wanting to work.

**Comment by izuzak** [comment]
@reecebisel This problem was fixed, but a new stable version of Atom with this change hasn't been published yet. If you build Atom from source, you'll should see the problem fixed, or you can just wait for the next stable release.
