### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, open 'C:\Users\blubaj\.atom\compile-cache\less\78e4a...

### ISSUE THREAD

**Issue by JestonBlu** [atom/settings-view#653]
[Enter steps to reproduce below:]

1. Attempting to change Syntax theme on a split pane
2. Error says too many files are open, however I only have one .html file open in the opposite pane.

**Atom Version**: 1.0.13
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught Error: EMFILE: too many open files, open 'C:\Users\blubaj\.atom\compile-cache\less\78e4afcbc1e8b319e7ae995093ed6230a82e105c\imports.json'

```
At fs.js:549

Error: EMFILE: too many open files, open 'C:\Users\blubaj\.atom\compile-cache\less\78e4afcbc1e8b319e7ae995093ed6230a82e105c\imports.json'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.writeFileSync (fs.js:1165:15)
  at Object.fsPlus.writeFileSync (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
  at LessCache.module.exports.LessCache.writeJson (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
  at LessCache.module.exports.LessCache.setImportPaths (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
  at LessCompileCache.module.exports.LessCompileCache.setImportPaths (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\less-compile-cache.js:32:25)
  at ThemeManager.module.exports.ThemeManager.refreshLessCache (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\theme-manager.js:421:75)
  at C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\theme-manager.js:355:17
  at C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:570:16
  at C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:587:20
  at Emitter.module.exports.Emitter.emit (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:772:29)
  at Config.module.exports.Config.setRawValue (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:564:19)
  at Config.module.exports.Config.set (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:233:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:487:28)
  at C:\Users\blubaj\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:494:24

```

### Commands

```
     -1:54.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:53.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:53.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:52.5.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -1:51.7.0 core:delete (atom-text-editor.editor.is-focused)
     -1:44.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:44 core:move-down (atom-text-editor.editor.is-focused)
     -1:42.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:42.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:41.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:35.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:06.1.0 editor:auto-indent (atom-text-editor.editor.is-focused)
     -0:57.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:56.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:55.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:55.2.0 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Git",
    "themes": [
      "atom-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
antialiased, v0.1.0
atom-runner, v2.4.3
autoclose-html, v0.19.0
autocomplete-julia, v0.1.0
color-picker, v2.0.11
file-icons, v1.6.9
ink, v0.1.1
javascript-snippets, v1.0.0
jsformat, v0.9.0
language-julia, v0.4.1
language-latex, v0.6.1
language-r, v0.2.0
latex, v0.25.1
local-server-express, v0.3.1
markdown-table-formatter, v2.5.3
markdown-themeable-pdf, v0.9.0
minimap, v4.13.3
pigments, v0.15.0
pretty-json, v0.4.1
preview-inline, v0.4.4
repl-term, v0.2.2
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Should be fixed with https://github.com/atom/atom/pull/8927
