### ISSUE TITLE
Failed to load the linter-jscs package

### ISSUE THREAD

**Issue by troyhart** [atom/settings-view#654]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.11.0-12-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to load the linter-jscs package

```
At true === false

AssertionError: true === false
  at Def.Dp.bases (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/ast-types/lib/types.js:408:12)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/babel/patch.js:22:13)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/babel/util.js:19:1)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/babel/transformation/file.js:33:36)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/babel/transformation/index.js:13:28)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/babel-core/lib/babel/api/node.js:14:23)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at transpile (/usr/share/atom/resources/app/src/babel.js:126:15)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:165:67)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:464:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  3x -4:00.1 core:select-down (atom-text-editor.editor)
     -3:59.4 core:select-right (atom-text-editor.editor)
     -3:58.5 core:select-left (atom-text-editor.editor)
     -3:57.6 core:backspace (atom-text-editor.editor)
     -3:54.0 core:save (atom-text-editor.editor)
     -2:36.2 settings-view:open (atom-text-editor.editor)
 23x -1:57.2 core:backspace (atom-text-editor.editor.mini)
     -1:13.5 core:cancel (div.settings-view.pane-item)
     -0:31.1 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
atom-jshint, v1.5.0
autocomplete-plus, v2.7.1
compass, v0.7.5
linter-jscs, v3.0.0
project-manager, v1.15.5
seti-syntax, v0.4.0
seti-ui, v0.6.3
tabs-to-spaces, v0.9.0
terminal-status, v1.6.6
trailing-spaces, v0.2.5
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
You're running a very, very old version of Atom - please update to the latest version (1.0.15).
