### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gocarlos** [atom/settings-view#655]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\settings-view.js:273

TypeError: Cannot convert undefined or null to object
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\settings-view.js:273:44)
  at SettingsView.module.exports.SettingsView.showPanel (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\settings-view.js:313:24)
  at openPanel (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\main.js:41:25)
  at C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\main.js:69:13
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:446:22)
  at Workspace.module.exports.Workspace.open (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:379:19)
  at HTMLAnchorElement.<anonymous> (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\about\lib\about-view.js:131:31)
  at space-pen-div.jQuery.event.dispatch (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\gocarlos\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
minimap, v4.13.3
pigments, v0.15.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hey @gocarlos, what were you doing when this exception occurred?  If you can consistently reproduce it, it would also be great to see if you can reproduce the issue in safe mode (`atom --safe`).  Thanks!

**Comment by raulfpl** [comment]
This exact exception happens when I do the following steps:
1. Open Atom
2. Select "Welcome Guide" in the "Help" menu
3. Click the "atom/metrics" package link at the welcome tab

**Comment by rsese** [comment]
If you have steps to reproduce in safe mode @khaninejad, please open a new issue and fill out the issue template and we'll take a look!

**Comment by khaninejad** [comment]
@rsese not accrued in the safe mode.

**Comment by rsese** [comment]
If there's no problem in safe mode, then that likely means a community package or possibly something in your init script is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable each community package one by one to try and pinpoint which is causing the problem.
