### ISSUE TITLE
Uncaught TypeError: disposable.dispose is not a function

### ISSUE THREAD

**Issue by JBLeung** [atom/settings-view#656]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught TypeError: disposable.dispose is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25

TypeError: disposable.dispose is not a function
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
  at Provider.module.exports.Provider.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:42:39)
  at Disposable.disposalAction (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:36:20)
  at Disposable.module.exports.Disposable.dispose (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/disposable.js:26:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
  at Package.module.exports.Package.deactivateResources (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:15)
  at Package.module.exports.Package.deactivate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:674:12)
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:535:12)
  at PackageManager.module.exports.PackageManager.uninstall (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:400:23)
  at PackageCard.module.exports.PackageCard.uninstall (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:671:34)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:288:24)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
clang-format, v1.16.0
formatter, v2.12.3
formatter-clang-format, v0.1.1

# Dev
No dev packages
```

**Comment by Trudko** [comment]
I am having same issue for few weeks now too. Happens when I update existing packages.


**Atom Version**: 1.7.2
**System**: Ubuntu 14.04
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: disposable.dispose is not a function

```
At /opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25

TypeError: disposable.dispose is not a function
    at /opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at /opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at Provider.module.exports.Provider.destroy (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:42:39)
    at Disposable.disposalAction (/opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:36:20)
    at Disposable.module.exports.Disposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/disposable.js:26:16)
    at /opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at Package.module.exports.Package.deactivateResources (/opt/atom/resources/app.asar/src/package.js:674:15)
    at Package.module.exports.Package.deactivate (/opt/atom/resources/app.asar/src/package.js:635:12)
    at PackageManager.module.exports.PackageManager.deactivatePackage (/opt/atom/resources/app.asar/src/package-manager.js:622:12)
    at PackageManager.module.exports.PackageManager.update (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:366:23)
    at PackageCard.module.exports.PackageCard.update (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:705:34)
    at HTMLButtonElement.<anonymous> (/opt/atom/resources/app.asar/node_modules/settings-view/lib/updates-panel.js:75:112)
    at HTMLButtonElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:17.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.use-animations.theme-atom-material-syntax.theme-atom-material-ui.has-custom-icons)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "linter-eslint",
      "sass-watch",
      "esformatter",
      "activate-power-mode"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      "node_modules",
      "bower_components"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
angularjs-styleguide-snippets, v0.7.3
atom-jade, v0.3.0
atom-jasmine, v0.8.1
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
atom-ternjs, v0.14.1
atom-yeoman, v0.3.15
auto-detect-indentation, v1.0.0
auto-reveal-in-sidebar, v0.8.0
autocomplete-angular-material, v0.4.0
color-picker, v2.1.1
exception-reporting, v0.38.1
express-complete, v0.2.0
file-icons, v1.7.8
formatter, v2.12.3
formatter-jsbeautify, v1.0.1
highlight-selected, v0.11.2
imdone-atom, v1.3.29
javascript-snippets, v1.2.1
jshint, v1.8.5
last-cursor-position, v0.9.0
less-than-slash, v0.13.0
linter, v1.11.4
linter-bootlint, v1.0.2
linter-htmlhint, v1.1.2
linter-sass-lint, v1.3.1
live-archive, v0.1.15
local-history, v3.2.3
metrics, v0.53.1
node-debugger, v1.4.7
nodejs-snippets, v2.0.0
pigments, v0.26.0
pretty-json, v1.0.3
project-manager, v2.9.7
react, v0.15.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by KolyaKorruptis** [comment]
Same here, also on updating a package.
