### ISSUE TITLE
Uncaught TypeError: this.pack.activateConfig is not a function

### ISSUE THREAD

**Issue by alexschneider** [atom/settings-view#658]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: linux 4.1.6-1-ARCH
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught TypeError: this.pack.activateConfig is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212

TypeError: this.pack.activateConfig is not a function
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:156:12)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:188:26
  at Request._callback (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:114:18)
  at Request.self.callback (/usr/share/atom/resources/app.asar/node_modules/request/request.js:123:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/request/request.js:1047:14)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:169:7)
  at IncomingMessage.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/request/request.js:998:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
     -9:29.9.0 core:paste (atom-text-editor#linter-tidy.tidyExecutablePath.editor.mini.is-focused)
     -8:46.1.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  2x -8:45.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:44.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:44.5.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  3x -7:43 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:28.1.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  3x -4:26.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -4:26.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
highlight-selected, v0.10.1
linter-htmlhint, v0.1.1
linter-jscs, v3.0.0
linter-jshint, v1.2.0
linter-tidy, v1.0.1
minimap, v4.13.3
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
minimap-pigments, v0.1.6
minimap-selection, v4.3.0
pigments, v0.15.0
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by Khady** [comment]
Still facing the issue:


**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Debian GNU/Linux
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.244.0


### Stack Trace

Uncaught TypeError: this.pack.activateConfig is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216

TypeError: this.pack.activateConfig is not a function
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:160:12)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:192:26
    at Request._callback (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:123:18)
    at Request.self.callback (/usr/share/atom/resources/app.asar/node_modules/request/request.js:123:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/request/request.js:1047:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/request/request.js:998:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -9:15.5.0 settings-view:open (input.hidden-input)
     -9:11.2.0 core:backspace (input.hidden-input)
     -9:10.5.0 core:confirm (input.hidden-input)
     -5:38.4.0 core:close (div.panels)
     -5:34.6.0 settings-view:open (input.hidden-input)
  7x -5:33.4.0 core:backspace (input.hidden-input)
     -2:52.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:18.1.0 core:confirm (input.hidden-input)
     -1:34.9.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:33.5.0 core:page-up (input.hidden-input)
     -1:30.5.0 core:confirm (input.hidden-input)
  5x -0:33.6.0 core:backspace (input.hidden-input)
     -0:28.3.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "vim-mode",
      "ex-mode",
      "tree-ignore",
      "revert-buffer",
      "terminal-plus",
      "language-source-cfg",
      "tabs",
      "smart-tags",
      "emacs-plus",
      "atom-languageclient"
    ],
    "packagesWithKeymapsDisabled": [
      "find-and-replace",
      "trailing-semicolon",
      "highlight-line"
    ],
    "projectHome": "/home/louis/Code",
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (inactive)
atom-languageclient, v1.0.7 (inactive)
atom-material-syntax, v1.0.2 (inactive)
atom-material-syntax-dark, v0.2.7 (inactive)
atom-material-syntax-light, v0.4.6 (inactive)
atom-material-ui, v1.3.9 (inactive)
autocomplete-paths, v1.0.5 (active)
autocomplete-python, v1.8.26 (active)
build, v0.67.0 (active)
build-make, v0.13.0 (active)
busy, v0.7.0 (active)
chester-atom-syntax, v0.1.1 (inactive)
clipboard-plus, v0.5.1 (active)
disable-keybindings, v0.6.0 (active)
emacs-plus, v0.11.1 (inactive)
file-icons, v2.0.9 (active)
filesize, v2.0.3 (active)
git-time-machine, v1.5.4 (inactive)
highlight-line, v0.12.0 (active)
highlight-selected, v0.12.0 (active)
hyperclick, v0.0.39 (active)
language-docker, v1.1.7 (active)
language-ocaml, v1.1.2 (active)
language-ocaml-fix, v1.5.3 (active)
linter, v1.11.21 (active)
linter-docker, v0.1.4 (active)
linter-flake8, v2.1.4 (inactive)
linter-jshint, v3.0.2 (active)
linter-ocaml, v1.2.0 (active)
loaded, v0.3.0 (inactive)
minimap, v4.26.6 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-hide, v0.3.0 (active)
minimap-highlight-selected, v4.5.0 (active)
minimap-linter, v1.6.0 (active)
minimap-split-diff, v0.3.2 (active)
monokai-seti, v0.7.0 (inactive)
ocaml-indent, v0.5.1 (inactive)
ocaml-merlin, v0.9.4 (inactive)
pigments, v0.38.0 (active)
project-plus, v0.9.0 (active)
python-indent, v1.0.0 (active)
python-tools, v0.6.9 (active)
Repl, v0.5.0 (active)
rest-client, v1.3.1 (active)
set-syntax, v0.3.2 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (inactive)
smart-tags, v0.1.5 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.1.1 (inactive)
sync-settings, v0.8.1 (active)
todo-show, v1.9.0 (inactive)
trailing-semicolon, v1.1.0 (inactive)
tree-view-git-status, v1.3.0 (active)
tree-view-open-files, v0.3.0 (active)
url-encode, v0.5.0 (inactive)
vim-mode-plus, v0.80.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by damieng** [comment]
Can you try and reproduce the issue by opening atom with `atom --safe` ?

**Comment by vmrob** [comment]
FWIW, I had the same issue after an uninstall of a pre 2.0 version of the linter-pycodestyle plugin. After I uninstalled that, it appeared that I *also* had a 2.0.0 version of the same plugin installed. After uninstalling that, the error went away.

**Comment by ssbarnea** [comment]
@vmrob So what's the final outcome? ... that we have to remove both `linter-pep8` and `linter-pycodestyle` from atom and get used to not linting Python code with Atom anymore? ;)

**Comment by vmrob** [comment]
@ssbarnea oh, I wasn't providing a workaround for linting. Just what I found to a symptom and workaround on my end. :P

**Comment by damieng** [comment]
Given that 100's of other packages work without this error I'd guess it's something wrong with either that package or a combination of packages conflicting.

**Comment by stevecshanks** [comment]
Not sure how helpful this is, but I had the samle problem and "resolved" it by uninstalling `language-ocaml` and `ocaml-merlin`.
