### ISSUE TITLE
Uncaught TypeError: Cannot read properties 'deactivateKeymaps' of undefined [and] Uncaught TypeError: Cannot read property 'activateKeymaps' of undefined

### ISSUE THREAD

**Issue by ron-wolf** [atom/settings-view#680]
1. Open Settings (cmd-,)
2. Go to the “Packages” pane
3. Find a package that comes with predefined keybindings
4. Click its “Settings” button
5. Scroll down to the “Keybindings” heading
6. Uncheck the box labelled “enabled”
7. Quit and reopen Atom
8. Open Settings (cmd-,)
9. Go to the “Settings” pane
10. Under “Core Settings”, find the “Packages With Keymaps Disabled” setting
 - Setting only only appears if it has a value, which we gave it in step 4
11. Add a comma and a space, as if you were about to add another item
 - An error “Uncaught TypeError: Cannot read property 'deactivateKeymaps' of undefined” should appear
12. Delete said comma and space
 - An error “Uncaught TypeError: annot read property 'activateKeymaps' of undefined” should appear

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

#### Entry at Step 11

Uncaught TypeError: Cannot read property 'deactivateKeymaps' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:339

TypeError: Cannot read property 'deactivateKeymaps' of undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:339:50
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:587:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:772:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:564:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:192:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:238:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1273:25

```

#### Deletion at Step 12

Uncaught TypeError: Cannot read property 'activateKeymaps' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:345

TypeError: Cannot read property 'activateKeymaps' of undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:345:50
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:587:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:772:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:564:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:192:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:238:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1273:25

```

#### Entry at Step 11

```
```

#### Deletion at Step 12

```
  2x -0:01.7.0 core:backspace (atom-text-editor#core.packagesWithKeymapsDisabled.editor.mini.is-focused)
```

#### Entry at Step 11

```json
{
  "core": {
    "projectHome": "/Users/Ronathan/Documents/Code/GitHub",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "browser-plus",
      "term"
    ],
    "packagesWithKeymapsDisabled": [
      "term2",
      ""
    ]
  }
}
```

#### Deletion at Step 12

```json
{
  "core": {
    "projectHome": "/Users/Ronathan/Documents/Code/GitHub",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "browser-plus",
      "term"
    ],
    "packagesWithKeymapsDisabled": [
      "term2"
    ]
  }
}
```

#### User
color-picker, v2.0.12
file-icons, v1.6.9
markdown-preview-plus, v2.1.1
minimap, v4.13.4
pigments, v0.15.0

#### Dev
No dev packages

**Comment by kevinsawicki** [comment]
I believe this has been fixed as #695
