### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/home/jll/.atom/compile-cache/less/987c0cc49a697...

### ISSUE THREAD

**Issue by woshidag** [atom/settings-view#685]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught Error: EACCES: permission denied, open '/home/jll/.atom/compile-cache/less/987c0cc49a697ef7383007a1a7db195ff60e8132/imports.json'

```
At fs.js:97

Error: EACCES: permission denied, open '/home/jll/.atom/compile-cache/less/987c0cc49a697ef7383007a1a7db195ff60e8132/imports.json'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.writeFileSync (fs.js:1165:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
  at LessCache.module.exports.LessCache.writeJson (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:155:17)
  at LessCache.module.exports.LessCache.setImportPaths (/usr/share/atom/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)
  at LessCompileCache.module.exports.LessCompileCache.setImportPaths (/usr/share/atom/resources/app.asar/src/less-compile-cache.js:32:25)
  at ThemeManager.module.exports.ThemeManager.refreshLessCache (/usr/share/atom/resources/app.asar/src/theme-manager.js:421:75)
  at /usr/share/atom/resources/app.asar/src/theme-manager.js:355:17
  at /usr/share/atom/resources/app.asar/src/config.js:570:16
  at /usr/share/atom/resources/app.asar/src/config.js:587:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:772:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:564:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:233:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/themes-panel.js:487:28)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/themes-panel.js:494:24

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
angularjs-snippets, v0.10.18
javascript-snippets, v1.0.0
jsformat, v0.9.0
linter, v1.8.1
meteor-api, v2.20.0
minimap, v4.13.4
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please make sure you have read/write permissions to your `%userprofile%/.atom` directory.
