### ISSUE TITLE
Failed to activate the highlight-selected package

### ISSUE THREAD

**Issue by salmander** [atom/settings-view#701]
[Enter steps to reproduce below:]

1. Open Settings/Preferences
2. Update All to update all packages

**Atom Version**: 0.187.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the highlight-selected package

```
At undefined is not a function

TypeError: undefined is not a function
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:355:117)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:243:16)
    at /usr/share/atom/resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:465:21)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:226:29
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
    at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
    at /usr/share/atom/resources/app/src/buffered-process.js:70:18
```

### Commands

```
     -0:14.2 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.11.1
language-blade, v0.16.0
laravel, v0.7.0
line-ending-converter, v1.3.2
php-cs-fixer, v2.5.1
pretty-json, v0.4.1
save-session, v0.15.3
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update Atom to the latest version (currently 1.2.0) - you're around 30 versions behind.
