### ISSUE TITLE
Uncaught Error: Undefined screen line when clipping screen position

### ISSUE THREAD

**Issue by m-pabon** [atom/settings-view#726]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.232.1

### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:886

Error: Undefined screen line when clipping screen position
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:874:15)
    at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:826:20)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadScreenPosition (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:185:60)
    at /Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:673:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1448:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1652:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1447:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:662:25)
    at HTMLDivElement.<anonymous> (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
    at EventEmitter.ipc.sendSync (/Users/Michael/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at Object.defineProperty.get [as windowState] (/Users/Michael/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:52)
    at Object.plus.mapObject (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at AtomEnvironment.module.exports.AtomEnvironment.getLoadSettings (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:464:14)
    at Function.module.exports.KeybindingsPanel.determineSource (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/keybindings-panel.js:256:43)
    at KeybindingsPanel.module.exports.KeybindingsPanel.elementForKeyBinding (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/keybindings-panel.js:209:33)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBinding (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/keybindings-panel.js:183:21)
    at KeybindingsPanel.module.exports.KeybindingsPanel.filterKeyBindings (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/keybindings-panel.js:160:30)
    at KeybindingsPanel.module.exports.KeybindingsPanel.loadKeyBindings (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/keybindings-panel.js:141:19)
    at KeybindingsPanel.module.exports.KeybindingsPanel.initialize (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/keybindings-panel.js:130:19)
    at KeybindingsPanel.View [as constructor] (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at KeybindingsPanel.ScrollView [as constructor] (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new KeybindingsPanel (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/keybindings-panel.js:18:53)
    at /Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:140:16
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Users/Michael/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:41.1.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @m-pabon, thanks for reporting!  Can you please share what you were doing when this happened?  Thanks.

**Comment by m-pabon** [comment]
Hi I downloaded atom onto my computer and got a bunch of welcome tabs and tutorial tabs and etc. I then switch to the "untitled tab" in the editor and then the error was thrown. I closed it out and was able to resume working.

**Comment by FibreFoX** [comment]
Happened to mee too, I downloaded a fresh version of Atom on Windows 8.1 (1.5.3) and started to do some basic configuration inside the settings-tab. I changed from "One Dark" to "One Light" for both themes (ui and syntax). While doing this, I was connected to the internet via mobile hotspot (slow connection).

I wasn't able to reproduce it yet, but will try to reproduce it.

```
**Atom Version**: 1.5.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.232.3


### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position


At C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\display-buffer.js:886

Error: Undefined screen line when clipping screen position
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\display-buffer.js:874:15)
    at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\display-buffer.js:826:20)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadScreenPosition (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor-marker.js:185:60)
    at C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\cursor.js:673:7)
    at Cursor.module.exports.Cursor.setScreenPosition (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\cursor.js:65:19)
    at C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor.js:1476:23
    at TextEditor.module.exports.TextEditor.moveCursors (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor.js:1680:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor.js:1475:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor-component.js:704:25)
    at HTMLDivElement.<anonymous> (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor-component.js:3:61)
    at EventEmitter.ipc.sendSync (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\remote.js:160:27)
    at Object.windowState (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:287:37)
    at Object.plus.deepClone (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:15:15)
    at AtomEnvironment.module.exports.AtomEnvironment.getLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:464:14)
    at Function.module.exports.KeybindingsPanel.determineSource (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:256:43)
    at KeybindingsPanel.module.exports.KeybindingsPanel.elementForKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:209:33)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:183:21)
    at KeybindingsPanel.module.exports.KeybindingsPanel.filterKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:160:30)
    at KeybindingsPanel.module.exports.KeybindingsPanel.loadKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:141:19)
    at KeybindingsPanel.module.exports.KeybindingsPanel.initialize (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:130:19)
    at KeybindingsPanel.View [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at KeybindingsPanel.ScrollView [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new KeybindingsPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:18:53)
    at C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:140:16
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
    at EventEmitter.ipc.sendSync (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\remote.js:160:27)
    at Object.windowState (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:287:37)
    at Object.plus.deepClone (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:15:15)
    at AtomEnvironment.module.exports.AtomEnvironment.getLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:464:14)
    at Function.module.exports.KeybindingsPanel.determineSource (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:256:43)
    at KeybindingsPanel.module.exports.KeybindingsPanel.elementForKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:209:33)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:183:21)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:173:28)
    at KeybindingsPanel.module.exports.KeybindingsPanel.loadKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:140:12)
    at KeybindingsPanel.module.exports.KeybindingsPanel.initialize (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:130:19)
    at KeybindingsPanel.View [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at KeybindingsPanel.ScrollView [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new KeybindingsPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:18:53)
    at C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:140:16
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
    at EventEmitter.ipc.sendSync (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\remote.js:160:27)
    at Object.windowState (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:287:37)
    at Object.plus.deepClone (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:15:15)
    at AtomEnvironment.module.exports.AtomEnvironment.getLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:464:14)
    at Function.module.exports.KeybindingsPanel.determineSource (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:256:43)
    at KeybindingsPanel.module.exports.KeybindingsPanel.elementForKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:209:33)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:183:21)
    at KeybindingsPanel.module.exports.KeybindingsPanel.filterKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:160:30)
    at KeybindingsPanel.module.exports.KeybindingsPanel.loadKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:141:19)
    at KeybindingsPanel.module.exports.KeybindingsPanel.initialize (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:130:19)
    at KeybindingsPanel.View [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at KeybindingsPanel.ScrollView [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new KeybindingsPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:18:53)
    at C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:140:16
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
    at EventEmitter.ipc.sendSync (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at Object.defineProperty.get [as windowState] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\remote.js:160:27)
    at Object.windowState (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:17:52)
    at Object.plus.mapObject (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:287:37)
    at Object.plus.deepClone (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:15:15)
    at AtomEnvironment.module.exports.AtomEnvironment.getLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:464:14)
    at Function.module.exports.KeybindingsPanel.determineSource (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:256:43)
    at KeybindingsPanel.module.exports.KeybindingsPanel.elementForKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:209:33)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:183:21)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:173:28)
    at KeybindingsPanel.module.exports.KeybindingsPanel.loadKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:140:12)
    at KeybindingsPanel.module.exports.KeybindingsPanel.initialize (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:130:19)
    at KeybindingsPanel.View [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at KeybindingsPanel.ScrollView [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new KeybindingsPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:18:53)
    at C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:140:16
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
    at EventEmitter.ipc.sendSync (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\remote.js:160:27)
    at Object.windowState (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:287:37)
    at Object.plus.deepClone (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-load-settings-helpers.js:15:15)
    at AtomEnvironment.module.exports.AtomEnvironment.getLoadSettings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:464:14)
    at Function.module.exports.KeybindingsPanel.determineSource (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:256:43)
    at KeybindingsPanel.module.exports.KeybindingsPanel.elementForKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:209:33)
    at KeybindingsPanel.module.exports.KeybindingsPanel.appendKeyBinding (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:183:21)
    at KeybindingsPanel.module.exports.KeybindingsPanel.filterKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:160:30)
    at KeybindingsPanel.module.exports.KeybindingsPanel.loadKeyBindings (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:141:19)
    at KeybindingsPanel.module.exports.KeybindingsPanel.initialize (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:130:19)
    at KeybindingsPanel.View [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at KeybindingsPanel.ScrollView [as constructor] (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new KeybindingsPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\keybindings-panel.js:18:53)
    at C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:140:16
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\someuser\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)


### Commands


  2x -1:59.2.0 editor:newline (atom-text-editor.editor.is-focused)


### Config

{
  "core": {
    "automaticallyUpdate": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}


### Installed Packages

# User
No installed packages

# Dev
No dev packages
```
