### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by ayontulip** [atom/settings-view#742]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [image2react](https://github.com/ganarajpr/image2react) package, v0.5.3

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At /C:/Users/Ayon/.atom/packages/image2react/lib/image2react.js:84

TypeError: editor.getPath is not a function
    at Image2react.onActivePaneChange (C:/Users/Ayon/.atom/packages/image2react/lib/image2react.js:58:33)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:312:19)
    at Pane.module.exports.Pane.activatePreviousItem (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:402:16)
    at Pane.module.exports.Pane.destroyItem (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:464:16)
    at atom-tabs.TabBarView.onClick (C:\Users\Ayon\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:695:17)
```

### Commands

```
  2x -6:23.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -5:48.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:48.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:38.7.0 core:select-all (atom-text-editor.editor.is-focused)
  9x -5:36.4.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -5:02.7.0 find-and-replace:toggle (atom-text-editor.editor.is-focused)
     -5:00.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:00.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:46.9.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -4:45.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:45.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:42.1.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -4:41.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:41.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:57 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angular2-snippets, v0.3.0
angularjs, v0.3.4
atom-beautify, v0.28.24
atom-ember-author-kit, v0.6.6
atom-react-native-css, v0.0.4
autocomplete-angular-material, v0.4.0
build-ember, v0.0.1
color-picker, v2.1.1
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
ember-tabs, v2.2.0
image2react, v0.5.3
language-blade, v0.20.0
language-coffee-script-angular, v2.2.0
language-ejs, v0.2.0
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
laravel, v0.7.0
laravel-snippets, v2.1.0
node-debugger, v1.4.4
nodejs-snippets, v2.0.0
react, v0.14.1
react-es6-snippets, v0.3.0
react-snippets, v0.3.0
sass-compiler, v0.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Closing in favor of ganarajpr/image2react#1.

**Comment by saikiran5** [comment]
how to solve this issue
