### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by Arcanemagus** [atom/settings-view#753]
[Enter steps to reproduce below:]

1. This was thrown while attempting to update:
    *  `atom-typescript@8.3.2` to `atom-typescript@8.4.0`
    *  `linter-jscs@3.4.9` to `linter-jscs@3.4.10`

**Atom Version**: 1.7.0-beta0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.0

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-card.js:692

TypeError: Cannot read property 'substr' of null
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-card.js:692:80
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:18
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -2:40.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:27.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "fast-eslint",
      "linter-flow",
      "atom-typescript",
      "markdown-preview-plus",
      "git-control",
      "git-history",
      "linter-gjslint",
      "language-markdown",
      "linter-tidy",
      "language-chef",
      "linter-csslint",
      "linter-bootlint",
      "linter-scss-lint",
      "linter-jscs"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.26
autocomplete-python, v1.7.0
docblockr, v0.7.3
editorconfig, v1.2.4
file-watcher, v0.4.0
highlight-selected, v0.11.2
language-docker, v1.1.6
language-elixir, v0.12.3
language-haml, v0.23.15
language-ini, v1.14.0
language-powershell, v2.1.0
language-r, v0.4.0
language-reg, v0.0.0
linter, v1.11.3
linter-alex, v2.0.0
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
linter-elixirc, v1.1.5
linter-erb, v1.0.2
linter-eslint, v7.1.1
linter-flake8, v1.13.0
linter-foodcritic, v0.5.2
linter-golinter, v1.2.0
linter-haml, v1.2.0
linter-htmlhint, v1.1.0
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jshint, v2.0.3
linter-jsonlint, v1.2.1
linter-lintr, v1.0.4
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pep8, v1.2.1
linter-perl, v0.7.2
linter-perlcritic, v0.3.3
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-pylint, v1.2.0
linter-rails-best-practices, v0.2.2
linter-reek, v2.1.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-stylelint, v2.0.1
linter-tslint, v0.8.3
linter-ui-default, v0.0.2
mapfile-grammar, v0.1.0
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
pigments, v0.24.5
seti-syntax, v0.4.1
seti-ui, v0.9.1
svn, v0.0.9
tab-control, v0.6.9
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Inside the interface it showed some more information:
![image](https://cloud.githubusercontent.com/assets/427137/13884526/9b4a52b2-eceb-11e5-8343-560199f65414.png)

**Comment by zedxxx** [comment]
[Enter steps to reproduce below:]

1. Trying update from 3.6.2 to 3.6.3

**Atom Version**: 1.7.0-beta0
**System**: Windows 8.1 x64
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.0


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\zed\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-card.js:692

TypeError: Cannot read property 'substr' of null
    at C:\Users\zed\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-card.js:692:80
    at C:\Users\zed\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:18
    at C:\Users\zed\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\zed\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\zed\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\zed\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "linter-flake8"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.5
autocomplete-python, v1.7.2
builder-go, v1.0.0
go-config, v1.1.2
go-get, v1.0.2
go-plus, v4.1.0
gofmt, v1.1.3
gometalinter-linter, v1.1.0
gorename, v1.0.0
linter, v1.11.4
navigator-godef, v1.0.2
tester-go, v1.0.3

# Dev
No dev packages
```
Output:
```
Updating to “script@3.6.3” failed.Hide output…
Failed to install script because Git was not found.

The script package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.
```
I have installed and worked git for windows:
```
Microsoft Windows [Version 6.3.9600]
(c) Корпорация Майкрософт (Microsoft Corporation), 2013. Все права защищены.

b:\>git --version
git version 2.7.0.windows.1

b:\>apm -v
apm  1.8.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.0.windows.1
visual studio
```

**Comment by kaflan** [comment]
$ apm -v            
apm  1.9.2          
npm  2.13.3         
node 0.10.40        
python 2.7.11       
git 2.7.1.windows.1 
visual studio

**Comment by mbarnett** [comment]
[Enter steps to reproduce below:]

1. In Settings Update Tab, clicked Update button to update package atom-beautify from version 0.29.1 to 0.29.2

**Atom Version**: 1.7.0
**System**: Mac OS X 10.11.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
 14x -5:15.7.0 core:close (atom-text-editor.editor.is-focused)
     -4:59.7.0 settings-view:open (atom-pane.pane.active)
 17x -4:43.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:47.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-itunes, v0.5.0
atom-language-rust, v0.6.0
autocomplete-clang, v0.8.9
build-cmake, v0.3.3
language-ada, v1.1.0
language-cmake, v0.1.4

# Dev
No dev packages
```

**Comment by drupaladmin** [comment]
[Enter steps to reproduce below:]

1. Update remote-FTP from 0.7.20 to 0.8.0 and script from 3.6.3 to 3.7.1

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:29.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.20
atom-autocomplete-php, v0.18.7
autocomplete-php, v0.3.7
git-plus, v5.13.4
linter, v1.11.4
linter-php, v1.2.0
php-integrator-linter, v0.2.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Closing in favor of #766.
