### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by rzhikharevich** [atom/settings-view#758]
1. Open Settings.
2. Click Install.

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.232.3

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at Object.content (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:62:68)
    at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:48:21)
    at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:41:26)
    at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:38:17)
    at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.InstallPanel.content (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:34:19)
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
    at InstallPanel.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
    at InstallPanel.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new InstallPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:30:49)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:159:18
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:02.8.0 settings-view:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store .git"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.59.0
build-cargo, v0.13.0
environment, v1.2.0
language-arm, v1.2.2
language-rust, v0.4.6
language-x86, v1.0.1
linter, v1.11.4
racer, v0.18.0
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by camdroid** [comment]
I'm seeing a similar issue. Clean install of Atom (at least, I nuked everything I could find - config files, packages, Library support, then restarted and re-downloaded Atom) - but it throws this error when it tries to open. It doesn't even install the CLI for atom or apm.
