### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by mm54760** [atom/settings-view#785]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught URIError: URI malformed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/normalize-package-data/node_modules/hosted-git-info/index.js:38

URIError: URI malformed
    at decodeURIComponent (native)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/normalize-package-data/node_modules/hosted-git-info/index.js:38:36
    at Array.map (native)
    at Function.module.exports.fromUrl (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/normalize-package-data/node_modules/hosted-git-info/index.js:32:39)
    at InstallPanel.module.exports.InstallPanel.performSearchForQuery (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:262:38)
    at InstallPanel.module.exports.InstallPanel.performSearch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:256:21)
    at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:184:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:43.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
  3x -0:40.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  8x -0:36.7.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:34.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 15x -0:18.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:16.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:15.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jslint"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.11
linter, v1.11.4
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
mocha, v0.0.7
pretty-json, v1.0.3
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by damieng** [comment]
Do you have any repro steps?

**Comment by damieng** [comment]
No response to request for repro steps.
