### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages/autocomplete-python/...

### ISSUE THREAD

**Issue by clarkchen** [atom/settings-view#805]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/chenxi/.atom/packages/autocomplete-python/lib/definitions-view.coffee'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:1033

Error: ENOENT: no such file or directory, open '/Users/chenxi/.atom/packages/autocomplete-python/lib/definitions-view.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:584:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
  at Object.fs.readFileSync (fs.js:431:33)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:221:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:329:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:337:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:289:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:355:34
  at Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:358:7)
  at Function.prepareStackTraceWithRawStackAssignment (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:174:12)
  at Package.module.exports.Package.handleError (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:1033:31)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:121:26
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:536:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
     -1:12.1.0 command-palette:toggle (atom-pane.pane.active)
     -1:11.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:11.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:10.7.0 settings-view:open (atom-pane.pane.active)
     -1:07.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:06.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:30.6.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 application:new-file (atom-pane.pane.active)
     -0:28 settings-view:open (atom-text-editor.editor.is-focused)
     -0:25.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-prettify",
      "tidy-markdown"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-python-test, v0.1.8
autocomplete-python, v1.8.1
markdown-image-helper, v1.0.4
markdown-scroll-sync, v2.1.2
markdown-themeable-pdf, v1.0.1
pretty-json, v1.2.0
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by bastilian** [comment]
When does this error occur and does `/Users/chenxi/.atom/packages/autocomplete-python/lib/definitions-view.coffee` exist on file?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to the questions in comment https://github.com/atom/settings-view/issues/805#issuecomment-229585744. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
