### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by holidaying** [atom/settings-view#810]
C:\Users\Administrator\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

**Comment by bastilian** [comment]
@holidaying can you provide more information when this error occurs and how to reproduce it?

**Comment by holidaying** [comment]
maybe the software's version,and download the new version ,it is ok now.

**Comment by 50Wliu** [comment]
Thanks for reporting back @holidaying!

**Comment by dmatthe4952** [comment]
I am also experiencing this problem on a linux ubuntu machine. I have atom1.0.2 installed. Install-packages tries to install go-plus 3.5.4:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 16.04.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0


### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
    at ErrorView.module.exports.ErrorView.initialize (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
    at ErrorView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ErrorView (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/install-panel.js:156:44
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:359:17
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:384:20
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
```

### Commands

```
     -0:46.3.0 settings-view:install-packages-and-themes (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:18.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
html-id-class-snippets, v1.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@dmatthe4952 You are running an extremely outdated version of Atom - the latest version is currently Atom 1.15.0.  I would highly recommend that you update.
