### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/Library/Application Support/Atom/Cac...

### ISSUE THREAD

**Issue by nayucolony** [atom/settings-view#850]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.242.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/yuki/Library/Application Support/Atom/Cache/settings-view/AtomLinter-1474338716414'

```
At fs.js:990

Error: ENOENT: no such file or directory, unlink '/Users/yuki/Library/Application Support/Atom/Cache/settings-view/AtomLinter-1474338716414'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:990:18)
    at WriteStream.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:221:18)
    at emitOne (events.js:95:20)
    at WriteStream.emit (events.js:182:7)
    at WriteStream.<anonymous> (fs.js:1933:12)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -6:53.9.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  2x -6:52.8.0 core:save (atom-text-editor.editor.is-focused)
     -6:21 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -6:20.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:30.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:26.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -3:25.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:23 core:copy (atom-text-editor.editor.is-focused)
     -1:10.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:04.4.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -1:03.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:47.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:40.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pug",
      "react"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.12 (active)
atom-css-comb, v3.1.0 (inactive)
atom-jade, v0.3.0 (active)
atom-material-syntax, v0.4.6 (active)
atom-material-ui, v1.3.6 (active)
autocomplete-plus, v2.31.2 (active)
autocomplete-wordpress-hooks, v0.2.0 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.19 (active)
git-plus, v5.16.2 (inactive)
highlight-column, v0.5.1 (active)
japanese-menu, v1.8.0 (active)
language-babel, v2.36.3 (active)
language-jade, v0.7.1 (active)
language-pug, v0.0.17 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-eslint, v7.3.2 (active)
linter-jshint, v2.1.0 (active)
linter-php, v1.2.0 (active)
linter-pug, v1.3.0 (inactive)
linter-scss-lint, v3.0.4 (active)
merge-conflicts, v1.4.4 (active)
multi-cursor, v2.1.3 (inactive)
php-cs-fixer, v2.5.9 (active)
platformio-ide-terminal, v2.2.0 (active)
project-manager, v2.9.7 (active)
react, v0.16.0 (inactive)
slack-ui, v0.7.0 (inactive)
tabs-to-spaces, v1.0.2 (active)
wakatime, v6.0.10 (active)
wordpress-api, v1.2.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.2 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ZuBB** [comment]
confirm this

**Comment by eshaansharma** [comment]
Just installed "markdown-editor" package v2.6.1 and got this error.

**Comment by TommasoBertagnin** [comment]
Same error for me while trying to install **atom-pair**

Atom Version: 1.10.2
System: Mac OS X 10.11.6

**Comment by jacquescrocker** [comment]
I'm seeing this error when installing `atom-beautify`, i keep trying and no dice

**Comment by damieng** [comment]
https://github.com/atom/settings-view/commit/a6f5b63ff1216f237656b9c5037b8cbc9ad06bcf should take care of the ENOENT errors and will stop exceptions from the EACCES although not sure if the EACCES is an actual permission issue (this could hide that problem) or one of concurrency (this would solve that problem albeit in a brute-force kind of way)

**Comment by chfast** [comment]
It happened to me because the ~/.cache/Atom was created by root at some point.

**Comment by aonoloki** [comment]
So, this issue may be created by updating packages while using Atom as root. I've got this issue for some packages, and fixed it by using the command <code>apm update</code> as sudo. Using Atom as sudo should work too. However this issue will be prompted for each new update of these packages (I guess) while using Atom as non-root user. Got to see to fix this in a proper way.

**Comment by tomanistor** [comment]
@aonoloki `sudo apm update` worked for me too with a similar error for the language-haml package. Thanks.

**Comment by aonoloki** [comment]
@tomanistor Your welcome, share some tips is essential in the dev.

However, I fixed this with a simple trick. I've noted all the plugins updated as root, then deleted their folder in .atom/packages with a simple `rm -RF` from my terminal, and then re-install them as non-root with the `apm install` command. Error fixed !
