### ISSUE TITLE
Uncaught Error: Cannot find module 'electron'

### ISSUE THREAD

**Issue by MatthewHerbst** [atom/settings-view#856]
Couldn't even auto-create an issue since the url was too long...

[Enter steps to reproduce below:]
1. Atom -> Preferences...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.242.2
### Stack Trace

Uncaught Error: Cannot find module 'electron'

```
At module.js:341

Error: Cannot find module 'electron'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:14:11)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:443:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:26:23)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:389:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.createSettingsView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:136:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:45:36
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:504:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:439:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1134:19)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:246:18)
    at emitThree (events.js:115:20)
    at EventEmitter.emit (events.js:188:7)
```
### Commands

```
  4x -3:13.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:12.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:52.9.0 core:copy (atom-text-editor.editor.is-focused)
  2x -2:47.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:47.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:46.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:46.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:46.3.0 editor:indent (atom-text-editor.editor.is-focused)
 10x -2:42.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:34.4.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:31.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:31.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:29.1.0 core:paste (atom-text-editor.editor.is-focused)
     -2:28.4.0 core:undo (atom-text-editor.editor.is-focused)
     -2:26.2.0 core:paste (atom-text-editor.editor.is-focused)
  4x -2:13.2.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "vim-mode"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-import-js, v0.3.0 (active)
file-icons, v1.7.19 (active)
language-cypher, v0.3.0 (active)
language-haml, v0.24.0 (active)
language-thrift, v1.0.2 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-eslint, v7.3.2 (active)
linter-haml, v1.2.1 (active)
linter-javac, v1.9.4 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.2.0 (active)
linter-pylint, v1.2.2 (active)
linter-ruby, v1.2.2 (active)
linter-shellcheck, v1.2.0 (active)
linter-swiftc, v2.0.0 (active)
monokai, v0.18.0 (active)
pretty-json, v1.6.0 (active)
react, v0.16.0 (active)
Remote-FTP, v0.8.9 (active)
set-syntax, v0.3.0 (active)
seti-ui, v1.3.2 (active)
vim-mode, v0.65.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (active)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

I was able to fix this by manually installing `npm install -g electron` and restarting Atom.

**Comment by 50Wliu** [comment]
This should be resolved now that we're on a newer version of Electron.
