### ISSUE TITLE
Uncaught CssSyntaxError: <css input>:3:31: Unclosed quote

### ISSUE THREAD

**Issue by janklosowski** [atom/settings-view#900]
[Enter steps to reproduce below:]

1. Use ' character in "Font Family" input in Editor Settings.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.244.0

### Stack Trace

Uncaught CssSyntaxError: <css input>:3:31: Unclosed quote

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parse.js:35

CssSyntaxError: <css input>:3:31: Unclosed quote

  1 | atom-text-editor {
  2 |   font-size: 9px;
> 3 |   font-family: Source Code Pro', "Apple Color Emoji";
    |                               ^
  4 |   line-height: 1.5;
  5 | }

    at Input.error (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/input.js:113:22)
    at unclosed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/tokenize.js:57:21)
    at tokenize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/tokenize.js:167:29)
    at Parser.tokenize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parser.js:49:46)
    at Function.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parse.js:25:16)
    at transformDeprecatedShadowDOMSelectors (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:253:37)
    at StyleManager.addStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:148:23)
    at atom-workspace.module.exports.WorkspaceElement.updateGlobalTextEditorStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:73:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:200:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:262:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1417:25
```

### Commands

```
     -0:01.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "resonance-ui",
      "resonance-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
atom-html-preview, v0.1.22 (active)
file-icons, v2.0.9 (active)
language-haskell, v1.10.4 (active)
language-svg, v0.9.2 (active)
resonance-syntax, v0.2.0 (active)
resonance-ui, v0.11.0 (active)
svg-preview, v0.11.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by damieng** [comment]
You have entered single quotes into the font-family box in settings. Quotes should not be entered there.

**Comment by janklosowski** [comment]
Sure. Maybe it's me but I would rather expect some other indicator that the format is not right. Or maybe even ignoring the character in that case.

**Comment by damieng** [comment]
Unfortunately these settings pages are all dynamically generated at runtime based on a schema which does not at this time support validation outside the basic data type not support programmatic access to doing things like stripping/fixing up the field.

There is some major work happening on settings-view that will hopefully address this further down the line.

**Comment by damieng** [comment]
We actually have another thread open that's looking into what we can do about this - there are some options such as encoding the output although it's still a bit hit and miss. You can follow it https://github.com/atom/settings-view/issues/768
