### ISSUE TITLE
I started using atom recently and cannot change theme of atom. Please help.

### ISSUE THREAD

**Issue by adityaXXX** [atom/settings-view#907]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.243.1

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\dell\.atom\compile-cache\less\fb767adbf845eec7ed21b3a684b73b8575143d68\imports.json'

```
At fs.js:640

Error: EPERM: operation not permitted, open 'C:\Users\dell\.atom\compile-cache\less\fb767adbf845eec7ed21b3a684b73b8575143d68\imports.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:281:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.setImportPaths (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
    at LessCompileCache.module.exports.LessCompileCache.setImportPaths (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\less-compile-cache.js:32:25)
    at ThemeManager.module.exports.ThemeManager.refreshLessCache (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\theme-manager.js:389:53)
    at C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\theme-manager.js:325:19
    at C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:618:16
    at C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:826:29)
    at Config.module.exports.Config.setRawValue (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:612:19)
    at Config.module.exports.Config.set (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:227:14)
    at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:527:28)
    at C:\Users\dell\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:534:24
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete, v0.47.0 (inactive)
autocomplete-clang, v0.10.0 (active)
autocomplete-php, v0.3.7 (active)
black-ui, v0.3.2 (inactive)
blackboard, v1.0.0 (inactive)
gcc-make-run, v0.2.9 (active)
gpp-compiler, v3.0.7 (active)
linter, v1.11.18 (active)
linter-clang, v3.4.6 (active)
linter-eslint, v8.1.0 (active)
spacegray-black-syntax, v0.1.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Delete `C:\Users\dell\.atom\compile-cache` and try again.

**Comment by adityaXXX** [comment]
It worked, but shows failed to save config.cson
EPERM: operation not permitted, open 'C:\Users\dell\.atom\config.cson'

**Comment by 50Wliu** [comment]
Ok, it looks like something is wrong with the permissions of your `.atom` folder.  Try moving it to `C:\Users\dell\.atom-backup`. and Atom will create a brand-new one for you.

**Comment by adityaXXX** [comment]
Thank you. It worked.

**Comment by adityaXXX** [comment]
Oops.
gpp-compiler
auto-complete clang
etc cannot be installed

Installing “gpp-compiler@3.0.7” failed.Hide output…
Unable to download https://www.atom.io/api/packages/gpp-compiler/versions/3.0.7/tarball: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443
