### ISSUE TITLE
Failed to activate the settings-view package

### ISSUE THREAD

**Issue by VahidSa** [atom/settings-view#911]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.246.0

### Stack Trace

Failed to activate the settings-view package

```
At EBUSY: resource busy or locked, open 'C:\Users\VahiD\.atom\compile-cache\style-manager\3ce303315bc5f77543a4a879191a142de7931283'

Error: EBUSY: resource busy or locked, open 'C:\Users\VahiD\.atom\compile-cache\style-manager\3ce303315bc5f77543a4a879191a142de7931283'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:17)
    at StyleManager.addStyleSheet (/app.asar/src/style-manager.js:149:12)
    at Package.module.exports.Package.activateStylesheets (/app.asar/src/package.js:287:58)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:211:14)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
If this is still an issue, delete the `C:\Users\VahiD\.atom\compile-cache` folder and try again.
