### ISSUE TITLE
Uncaught Error: spawn UNKNOWN when opening system settings

### ISSUE THREAD

**Issue by az82** [atom/settings-view#922]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening Settings -> System reproducibly  causes "Uncaught Error: spawn UNKNOWN". The system settings page does not open.

Stack trace:
```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Registry.get (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\winreg\lib\registry.js:616:14)
    at ShellOption.isRegistered (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\src\main-process\win-shell.js:40:91)
    at SystemPanel.module.exports.SystemPanel.initialize (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\system-windows-panel.js:140:28)
    at SystemPanel.View [as constructor] (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\space-pen\lib\space-pen.js:184:25)
    at SystemPanel.ScrollView [as constructor] (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new SystemPanel (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\system-windows-panel.js:14:48)
    at C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:136:18
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\settings-view.js:114:24)
    at space-pen-div.dispatch (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\odq82wy\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Steps to Reproduce

1. Open "Settings"
2. Open "System"

**Expected behavior:** System page opens

**Actual behavior:** Error mesage

**Reproduces how often:** Every time

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
OS:  Windows 7 Enterprise SP 1 64bit

### Additional Information

![2017-03-15 15_12_25-settings atom](https://cloud.githubusercontent.com/assets/1633055/23952487/e31864a8-0991-11e7-901d-0316ad22fddb.png)

**Comment by damieng** [comment]
When you go into settings on Windows it needs to spawn the 'reg' command to be able to check and perform integration with the Windows registry.

I'm not sure why this is failing on your system especially with such an unusual error code (UNKNOWN).

Can you open a command prompt and type `REG` then press enter and make sure you don't see an error.

**Comment by damieng** [comment]
Additionally can you let us know how you launch atom. i.e. icon, command prompt, powershell, cygwin, git-bash.

**Comment by az82** [comment]
Thanks for the quick reply. That explains a lot actually. The computer in
question is a locked down corporate machine. Access to the reg command
without administrator privileges is blocked by group policy. I was not
aware that Atom uses the  I reg command to access the registry. I'll check
if it works with administrator privileges.



Am 15.03.2017 18:12 schrieb "Damien Guard" <notifications@github.com>:

When you go into settings on Windows it needs to spawn the 'reg' command to
be able to check and perform integration with the Windows registry.

I'm not sure why this is failing on your system especially with such an
unusual error code (UNKNOWN).

Can you open a command prompt and type REG then press enter and make sure
you don't see an error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atom/settings-view/issues/922#issuecomment-286813135>,
or mute the thread

**Comment by az82** [comment]
I tried launching atom with the icon and also with the windows command promt.
Access to the reg command is also blocked with administrative privileges.

**Comment by damieng** [comment]
Right now the settings view requires access to the reg command. It would seem weird to have blocked this given apps read and write the registry all the time and this just provides a command-line version of it (which we have to use from node in the absence of actual direct access via the api)

**Comment by az82** [comment]
I wholeheartedly agree.

**Comment by damieng** [comment]
The only real option here would be to try/catch around the registry access and disable the relevant settings with a tooltip that indicates 'reg' command is unavailable.
