### ISSUE TITLE
Uncaught TypeError: ref.dispose is not a function

### ISSUE THREAD

**Issue by Sija** [atom/settings-view#928]
1. Open *Updates* Settings section

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.247.0

### Stack Trace

Uncaught TypeError: ref.dispose is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-updates-status-view.js:148

TypeError: ref.dispose is not a function
    at PackageUpdatesStatusView.module.exports.PackageUpdatesStatusView.updateTile (/app.asar/node_modules/settings-view/lib/package-updates-status-view.js:148:15)
    at PackageUpdatesStatusView.module.exports.PackageUpdatesStatusView.onPackageUpdateAvailable (/app.asar/node_modules/settings-view/lib/package-updates-status-view.js:83:19)
    at /app.asar/node_modules/settings-view/lib/package-updates-status-view.js:43:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:217:21
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:32.4.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
ask-stack 2.2.0 
atom-mac-theme 0.4.2 
auto-detect-indentation 1.3.0 
base16-ocean-dark-spacegray 0.13.0 
bezier-curve-editor 0.7.2 
busy-signal 1.3.0 
color-picker 2.2.5 
command-logger 0.23.0 
crystal 0.2.0 
editor-stats 0.17.0 
editorconfig 2.2.2 
file-icons 2.1.1 
fizzy 0.21.0 
gist-it 0.9.2 
git-blame 0.4.12 
git-tab-status 1.9.2 
highlight-line 0.12.0 
highlight-selected 0.12.0 
intentions 1.1.2 
language-crystal-actual 0.33.0 
language-elixir 0.17.0 
language-haml 0.24.1 
linter 2.1.1 
linter-coffeelint 1.2.1 
linter-csslint 1.3.4 
linter-haml 2.0.1 
linter-htmlhint 1.3.2 
linter-js-yaml 1.2.7 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-mixed-indent 1.1.0 
linter-package-json-validator 1.0.1 
linter-php 1.3.2 
linter-rubocop 1.1.1 
linter-scss-lint 3.1.0 
linter-stylelint 3.9.0 
linter-stylint 2.2.7 
linter-tidy 2.3.1 
linter-ui-default 1.2.1 
linter-xmllint 1.4.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
monokai 0.22.0 
project-manager 3.3.4 
proton 4.0.2 
react 0.16.2 
seti-monokai 0.3.1 
seti-syntax 1.1.3 
seti-ui 1.7.0 
show-in-system 0.4.0 
spacegray-dark-ui 0.12.0 
spacegray-eighties-ui 1.2.0 
Stylus 3.1.0 
task-list 0.7.0 
todo-show 1.11.0 
toggle-quotes 1.0.1 
travis-ci-status 1.3.1 
Zen 0.16.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if it's reproducible in safe mode (atom --safe)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/928#issuecomment-289085826. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
