### ISSUE TITLE
Uncaught Error: Cannot find module 'html-pdf'

### ISSUE THREAD

**Issue by Mrfuture1** [atom/settings-view#933]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.247.0

### Stack Trace

Uncaught Error: Cannot find module 'html-pdf'

```
At module.js:457

Error: Cannot find module 'html-pdf'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (D:/Personal/Desktop/markdown-pdf/lib/markdown-pdf.js:2:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
    at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:665:24
    at /app.asar/node_modules/settings-view/lib/package-card.js:741:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:491:26
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
```

### Commands

```
     -1:57 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.20.0 
markdown-img-paste 0.3.8 
markdown-pdf 1.5.0 
markdown-scroll-sync 2.1.2 
sync-settings 0.8.1 
```

**Comment by rsese** [comment]
Can you confirm if you see the error in safe mode?  Based on the error, I'm wondering if the issue is with markdown-pdf /cc https://github.com/travs/markdown-pdf/issues/149.

**Comment by Mrfuture1** [comment]
I restart the atom.And now It is ok.
I think the issue can be closed.

**Comment by pradeepkumarpop** [comment]
> I restart the atom.And now It is ok. I think the issue can be closed.

what do you mean by restart the atom .
