### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setEncoding' of undefined

### ISSUE THREAD

**Issue by tottop** [atom/settings-view#938]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setEncoding' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:184

TypeError: Cannot read property 'setEncoding' of undefined
    at BufferedProcess.bufferStream (/app.asar/src/buffered-process.js:184:13)
    at BufferedProcess.handleEvents (/app.asar/src/buffered-process.js:333:14)
    at BufferedProcess.start (/app.asar/src/buffered-process.js:113:12)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:112:34
    at PackageManager.module.exports.PackageManager.applyProxyToEnv (/app.asar/node_modules/settings-view/lib/package-manager.js:84:14)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:66:28
    at CallbacksRegistry.apply (/Applications/Atom.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:275:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:17.6.0 application:reopen-project (atom-pane.pane.active)
     -1:05.2.0 core:paste (input.hidden-input)
     -1:03.7.0 core:undo (input.hidden-input)
     -0:54 core:paste (input.hidden-input)
     -0:53.6.0 core:confirm (input.hidden-input)
     -0:23.4.0 core:save (input.hidden-input)
  2x -0:22.7.0 core:select-all (input.hidden-input)
     -0:20.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atomify 0.3.0 
pigments 0.39.1 
spacegray-atom-dark-syntax 1.3.2 
```

**Comment by damieng** [comment]
Can you go into Atom Settings and uncheck `Use Proxy Settings When Calling APM` and see if that helps?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/938#issuecomment-294307992. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
