### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by gungunfebrianza** [atom/settings-view#943]
Hello, i was tried to install split-diff package. But it's seem there is something wrong.

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\sambaladokrist\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:240

TypeError: Cannot read property 'version' of undefined
    at /app.asar/node_modules/settings-view/lib/package-card.js:240:34
    at /app.asar/node_modules/settings-view/lib/package-manager.js:282:18
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -6:35.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-html-preview 0.1.22 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-ui-default 1.2.3 
minimap 4.27.1 
minimap-autohider 1.4.0 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
```

**Comment by rsese** [comment]
Is the error reproducible for you?  I just tried to install split-diff with Atom 1.16.0 on Windows 10 and didn't get any errors.

**Comment by Jesse-Millwood** [comment]
On a fresh install of windows, this is the first package that was attempted to be installed by "asciidoc-assitant" and I got this error. 

[Enter steps to reproduce:]

1. Fresh install of Atom on my Windows Machine
2. Tried to install asciidoc-assistant
3. This is the first thing I did when opening up Atom for the first time
4. Atom had never been installed on this machine before

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise 2015 LTSB
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\jessemillwood\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:240

TypeError: Cannot read property 'version' of undefined
    at /app.asar/node_modules/settings-view/lib/package-card.js:240:34
    at /app.asar/node_modules/settings-view/lib/package-manager.js:282:18
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -5:45.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-preview 2.10.1 
autocomplete-asciidoc 0.1.2 
language-asciidoc 1.10.0 
```

**Comment by jasonhubs** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:240

TypeError: Cannot read property 'version' of undefined
    at /app.asar/node_modules/settings-view/lib/package-card.js:240:34
    at /app.asar/node_modules/settings-view/lib/package-manager.js:282:18
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -6:18.9.0 core:confirm (input.hidden-input)
  4x -6:09.1.0 core:backspace (input.hidden-input)
     -6:05.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-runner 2.7.1 
atom-yii2 0.4.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
block-comment-plus 0.4.0 
browser-plus 0.0.87 
docblockr 0.9.4 
jquery-snippets 11.0.0 
kite 0.23.0 
minimap 4.28.2 
open-html-in-browser 0.1.0 
open-in-browsers 0.0.19 
platformio-ide-terminal 2.5.0 
python-autopep8 0.1.3 
vim-mode-plus 0.92.0 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by MinHyeok90** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:240

TypeError: Cannot read property 'version' of undefined
    at /app.asar/node_modules/settings-view/lib/package-card.js:240:34
    at /app.asar/node_modules/settings-view/lib/package-manager.js:282:18
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  8x -7:34.6.0 core:backspace (input.hidden-input)
  2x -6:59.6.0 core:confirm (input.hidden-input)
     -6:33.5.0 core:backspace (input.hidden-input)
  2x -1:23.4.0 window:decrease-font-size (a.)
  2x -1:17.8.0 window:increase-font-size (a.)
     -0:56.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-django 0.3.2 
autocomplete-python 1.8.63 
django-templates 0.5.0 
emmet 2.4.3 
git-blame 1.1.1 
python-indent 1.0.2 
python-tools 0.6.9 
sublime-block-comment 0.5.1 
```

**Comment by Leo-Mu** [comment]
# I meet it, too!

[Enter steps to reproduce:]

1. I clicked "help" > "check for update".
2. I minimized the window and opened it again, error thrown out.

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.249.4


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\mutou\AppData\Local\atom\app-1.18.0\resources\app\node_modules\settings-view\lib\package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-card.js:248:40
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-manager.js:317:24
    at exit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -9:06.2.0 core:paste (input.hidden-input)
     -9:05.1.0 core:backspace (input.hidden-input)
     -9:04.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-ternjs 0.18.3 
color-picker 2.2.5 
css-snippets 1.1.0 
markdown-preview-enhanced 0.14.3 
markdown-preview-plus 2.4.10 
markdown-writer 2.6.5 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.3.0 
webbox-color 0.5.9 
```

**Comment by rsese** [comment]
@Leo-Mu - is the error reproducible in safe mode (`atom --safe`) for you?

**Comment by Mr-Oops** [comment]
I saw it, too too too！

**Comment by rsese** [comment]
Do you have steps to reproduce @Mr-Oops?  And if so, can you reproduce in safe mode (`atom --safe`)?

**Comment by Mr-Oops** [comment]
I'll try it, thanks！o_o

**Comment by BillEliot** [comment]
When I installed 'markdown-writer', it occurred

Cannot read property 'version' of undefined
