### ISSUE TITLE
Fetching featured packages failed. Can't install packages and themes

### ISSUE THREAD

**Issue by bogdanostojic** [atom/settings-view#951]
### Prerequisites

[X ] Put an X between the brackets on this line if you have done all of the following:
[X ]  Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[X ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[X ]Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
[X ] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
[X ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

**When i open the settings tab to install packages or themes, or even the packages and theme tab cant load the installed, it just says loading packages/themes...**

**During the debugging guide when i tried to check all the commands for errors. Check for Linked Packages step caused the same error**

**This is under Check Font Rendering Issues in debugging :**
[[When i click back and forth packages and themes in the install tab the error stacks and the  Ctrl+Shift+I shows the console]](http://imgur.com/a/jQMmA) 

### Steps to Reproduce

~~1. I first tried uninstalling, reseting then installing again a newly downloaded atom.exe file. Same error
2. Uninstalled node.js then i got this error :
   'node.exe' is not recognized as an internal or external command, operable program or batch file.
   Installed the newest LTS from the site V6.10.3, same error as the first time.
3. Problem keeps repeating~~

*Edit: updated steps to reproduce by @rsese*

Tested on Windows 10, to repro:

1. Create a new user account named `SPACE!`
2. Install Atom
3. Open Settings > Install
4. Should see a `Fetching featured packages failed` error, click `Show output`.

In the expanded output you'll see:

> 'node.exe' is not recognized as an internal or external command, operable program or batch file.

**Expected behavior:** To preview like on my other machines, to work normal.

**Actual behavior:** [[What actually happens]](http://imgur.com/a/lOsZY)
                               [[Same for themes]](http://imgur.com/a/sjtkx)
                               [[For installed packages it stays at loading packages...]](http://imgur.com/a/iPQix)
This is under Check Font Rendering Issues in debugging :
[[When i click back and forth packages and themes in the install tab the error stacks and the  Ctrl+Shift+I shows the console]](http://imgur.com/a/jQMmA) 

**Reproduces how often:** 100%

### Versions

Atom : 1.16.0
Electron : 1.3.13
Chrome : 52.0.2743.82
Node : 6.5.0

Windows 10 Education 64-bit
Version : 1607
OS Build : 14393.1198

### Additional Information

Running the latest update from Windows 10, date is 15th May 2017

**Comment by joergmoldenhauer** [comment]
I have a similar issue. I can't view or install themes or packages. On themes page in settings I get "Fetching local packages failed." on install page I get "Fetching featured packages failed.". On packages page the packages are not loaded. In output message it says "the system was unable to find the path".

**Comment by bogdanostojic** [comment]
Don't really know what's going up with Atom. I just switched to  Visual Studio Code until I can get it working on my machine

**Comment by joergmoldenhauer** [comment]
I think the problem has something to do with environment variables. I am using Windows 7 and have no environment varibles set for atom. I think there should be an entry in "Path" or "PATH". Could somebody please tell me what the environment varibales for atom should be?

**Comment by rsese** [comment]
Sorry for missing this one @bogdanostojic - @bogdanostojic @joergmoldenhauer, can you share what you get from running `apm list` from cmd?

@joergmoldenhauer - on my Windows 10 machine `PATH` includes `C:\Users\robert\AppData\Local\atom\bin`.

**Comment by joergmoldenhauer** [comment]
@rsese Thanks for your response. I have the path to "...\atom\bin" in my PATH environment variable (with my username of course). There seem's to be something wrong with it, because I can not run atom commands on my cmd. I think this problem might be connected with the package loading problem. On my other computer I do not have these problems. There I can run atom commands and install packages and themes.

**Comment by bogdanostojic** [comment]
@rsese Thanks for replying. @joergmoldenhauer Sorry to hear that you are having the same problem as I do. I get this when i run **apm-list** :

>module.js:471
    throw err;
    ^

>Error: Cannot find module 'C:\Users\SPACE\AppData\Local\atom\app-1.18.0\resources\app\apm\lib\cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by rsese** [comment]
Yeah they seem like different issues - @bogdanostojic, can you confirm if there's anything in `C:\Users\SPACE\AppData\Local\atom\app-1.18.0\resources\app\apm\lib`?  Or even 1 directory above at `C:\Users\SPACE\AppData\Local\atom\app-1.18.0\resources\app\apm`?

**Comment by bogdanostojic** [comment]
Yeah seems so. @rsese, [here is apm\lib folder and app\apm](http://imgur.com/a/WM26g)

**Comment by rsese** [comment]
Thanks for the screenshots @bogdanostojic - I see your username in the screenshot is `SPACE!` with an exclamation point but the error message is showing your username without the `!`:

> Error: Cannot find module 'C:\Users\SPACE\AppData\Local\atom\app-1.18.0\resources\app\apm\lib\cli.js'

Makes sense why the file can't be found since your user directory is `C:\Users\SPACE!` - I can generate the `'node.exe' is not recognized as an internal or external command, operable program or batch file.` error from `Settings > Install` on my Windows 10 machine:

1. Create a new user account named `SPACE!`
2. Install Atom
3. Open `Settings > Install`

If I follow the same steps but name the account `SPACE` without the exclamation point, it works ok.

I don't know if there's a great workaround aside from creating a new account that doesn't end in a `!`?  I'm also not sure if this is an Atom issue or a Squirrel issue but tagging as a bug for now.

**Comment by bogdanostojic** [comment]
Sharp eyes @rsese, didn't notice that. I haven't tried it on that machine, but I have a same user on my laptop without the exclamation point and it works just fine, tried it on a Windows 7 machine as well, works good. 
Thanks a lot for the help.

**Comment by joergmoldenhauer** [comment]
Nice work finding that bug!

**Comment by Tooniis** [comment]
I'm having the same (or similar) issue on Arch Linux, with this output:
```
internal/modules/cjs/loader.js:1065
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/src/git.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

**Comment by dumb-stuff** [comment]
> @rsese Thanks for replying. @joergmoldenhauer Sorry to hear that you are having the same problem as I do. I get this when i run **apm-list** :
> 
> > module.js:471
> > throw err;
> > ^
> 
> > Error: Cannot find module 'C:\Users\SPACE\AppData\Local\atom\app-1.18.0\resources\app\apm\lib\cli.js'
> > at Function.Module._resolveFilename (module.js:469:15)
> > at Function.Module._load (module.js:417:25)
> > at Module.runMain (module.js:604:10)
> > at run (bootstrap_node.js:390:7)
> > at startup (bootstrap_node.js:150:9)
> > at bootstrap_node.js:505:3

I have this error same like you.

**Comment by bogdanostojic** [comment]
Hey @dumb-stuff , have you checked to see if your windows User name has any special characters in it?
