### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by marcelo21** [atom/settings-view#959]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.249.4

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At C:\Users\Marcelo\AppData\Local\atom\app-1.17.2\resources\app\node_modules\settings-view\lib\package-detail-view.js:257

TypeError: Cannot read property 'classList' of undefined
    at PackageDetailView.showLoadingMessage (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-detail-view.js:257:1)
    at PackageDetailView.fetchPackage (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-detail-view.js:240:1)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-detail-view.js:229:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-detail-view.js:548:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:687:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:526:1
    at exit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:1)
    at triggerExitCallback (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -7:05.4.0 core:confirm (input.hidden-input)
 50x -6:13.7.0 core:page-down (div.package-detail.panels-item)
 44x -6:04.1.0 core:page-up (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
autocomplete-python 1.8.64 
file-icons 2.1.7 
minimap 4.28.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by marcelo21** [comment]
Fix it once you remove the plugin you had installed

Saludos.

**Comment by rsese** [comment]
Just to clarify, it sounds like things are ok for you now that you uninstalled a particular package?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/959#issuecomment-307951599. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
