### ISSUE TITLE
Uncaught Error: read ENOTCONN

### ISSUE THREAD

**Issue by iczero** [atom/settings-view#960]
[Enter steps to reproduce:]

1. Open Settings
2. Switch to the System tab

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.249.4

### Stack Trace

Uncaught Error: read ENOTCONN

```
At events.js:160

Error: read ENOTCONN
    at exports._errnoException (util.js:1026:11)
    at Socket._read (net.js:417:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:300:43)
    at new Socket (net.js:180:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at exports.spawn (child_process.js:392:9)
    at Registry.get (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/winreg/lib/registry.js:616:14)
    at ShellOption.isRegistered (~/AppData/Local/atom/app-1.17.0/resources/app/src/main-process/win-shell.js:40:91)
    at new SystemPanel (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/system-windows-panel.js:53:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/settings-view.js:220:1
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/settings-view.js:361:1)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/settings-view.js:419:1)
    at HTMLDivElement.clickHandler (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/settings-view.js:186:1)
```

### Commands

```
  2x -5:34.9.0 timecop:view (input.hidden-input)
     -1:04.0 window:toggle-dev-tools (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
busy-signal 1.4.3 
intentions 1.1.2 
language-babel 2.65.1 
linter 2.1.4 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
merge-conflicts 1.4.5 
minimap 4.28.2 
wakatime 7.0.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if it's reproducible in safe mode (atom --safe)?

**Comment by iczero** [comment]
I tried it again, and it happens every time I switch to that tab.
It is reproducible in safe mode.

**Comment by iczero** [comment]
I fixed this issue. 
Apparently my windows installation was missing the Null service, causing a lot of applications (including atom) to fail when they try to redirect data to the NUL device. This was fixed by adding back the Null service.

**Comment by rsese** [comment]
Thanks for lettings us know what the issue was and how you fixed it :bow:
