### ISSUE TITLE
Uncaught Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by maliaaska** [atom/settings-view#969]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.249.4

### Stack Trace

Uncaught Error: Cannot find module 'tslib'

```
At /usr/share/atom/resources/app/static/<embedded>:1

Error: Cannot find module 'tslib'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/maliaaska/atom-typescript/dist/main/atomts.js:3:17)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:687:33)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:526:32
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -3:01.6.0 settings-view:open (input.hidden-input)
     -2:52.2.0 core:confirm (input.hidden-input)
     -0:35.2.0 settings-view:open (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-live-server 2.1.2 
atom-typescript 11.0.6 
busy-signal 1.4.3 
console-panel 0.2.1 
emmet 2.4.3 
intentions 1.1.2 
jshint 1.8.6 
linter 2.2.0 
linter-erb 1.1.0 
linter-ruby 1.2.5 
linter-ui-default 1.2.4 
linter-xo 0.23.1 
minimap 4.29.0 
minimap-git-diff 4.3.1 
package-cop 0.2.10 
platformio-ide-terminal 2.5.1 
sass-autocompile 0.13.3 
script 3.15.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-typescript](https://atom.io/packages/atom-typescript) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
