### ISSUE TITLE
Flaky test: it opens the settings to the correct panel with atom://config/<panel-name> and that panel is keyboard-scrollable

### ISSUE THREAD

**Issue by 50Wliu** [atom/settings-view#976]
#974: https://ci.appveyor.com/project/Atom/settings-view/build/307/job/ca3lch89qxuqurph
```
SettingsView
  when the package is activated
    when atom.workspace.open() is used with a config URI
      it opens the settings to the correct panel with atom://config/<panel-name> and that panel is keyboard-scrollable
        Expected false to be true.
          at .<anonymous> (file:///C:/projects/settings-view/spec/settings-view-spec.coffee:227:46)
          at _combinedTickCallback (internal/process/next_tick.js:67:7)
          at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by 50Wliu** [comment]
I can only reproduce this with the dev tools open.  Though tests should be run through the command line, which would mean there shouldn't be a dev tools to open...
