### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/usr/share/atom/resources/app/usr/share/...

### ISSUE THREAD

**Issue by vushe** [atom/settings-view#981]
It's really hard to figure out what might happen...

1. Github package was disabled about 2 weeks ago for some reason
2. Atom updated from 1.18.0 to 1.19.0 (to 1.19.1 today)
3. When activating Github package again, always receiving the error. What I noticed is that path to `_global.less` is incorrect.

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.250.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/usr/share/atom/resources/app/usr/share/atom/resources/app/usr/share/atom/resources/app/usr/share/atom/resources/app/usr/share/atom/resources/app/node_modules/github/styles/_global.less'

```
At /usr/share/atom/resources/app/src/theme-manager.js:323

Error: ENOENT: no such file or directory, open '/usr/share/atom/resources/app/usr/share/atom/resources/app/usr/share/atom/resources/app/usr/share/atom/resources/app/usr/share/atom/resources/app/node_modules/github/styles/_global.less'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:299:56)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/usr/share/atom/resources/app/src/theme-manager.js:271:27)
    at /usr/share/atom/resources/app/src/package.js:545:60
    at Array.map (native)
    at Package.module.exports.Package.loadStylesheets (/usr/share/atom/resources/app/src/package.js:543:65)
    at /usr/share/atom/resources/app/src/package.js:137:23
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.finishLoading (/usr/share/atom/resources/app/src/package.js:133:25)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:521:38)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:495:27)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app/src/package-manager.js:186:25)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -5:02.2.0 editor:consolidate-selections (input.hidden-input)
     -5:02.2.0 core:cancel (input.hidden-input)
     -5:00.0 core:backspace (input.hidden-input)
     -2:19.9.0 core:delete (input.hidden-input)
 11x -0:10.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-soda-dark-ui 1.1.0 
file-icons 2.1.10 
highlight-line 0.12.0 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
language-batch 0.4.0 
language-pug 0.0.21 
monokai-seti 0.9.0 
pigments 0.40.2 
seti-ui 1.9.0 
toggle-quotes 1.0.1 
trailing-spaces 0.4.0 
```

**Comment by vushe** [comment]
Ok, problem was probably in `atom-soda-dark-ui 1.1.0 `
Solved

**Comment by vushe** [comment]
It appears that issue may be related to [this one](https://github.com/atom/github/issues/978)

1. I removed `atom-soda-dark-ui 1.1.0 `
2. Activated Github package (successfully)
3. Tried to install `atom-soda-dark-ui 1.1.0 ` and was forwarded to the issue 978.
