### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open '$ATOM_HOME/compile-cache\less\40e22529c8729...

### ISSUE THREAD

**Issue by danielramos1981** [atom/settings-view#992]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.250.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\Daniel\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'

```
At fs.js:558

Error: EPERM: operation not permitted, open 'C:\Users\Daniel\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Proxy.writeFileSync (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/fs-plus/lib/fs-plus.js:298:29)
    at LessCache.module.exports.LessCache.writeJson (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/less-cache/lib/less-cache.js:212:23)
    at LessCache.module.exports.LessCache.setImportPaths (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/less-cache/lib/less-cache.js:161:18)
    at LessCompileCache.module.exports.LessCompileCache.setImportPaths (~/AppData/Local/atom/app-1.19.7/resources/app/src/less-compile-cache.js:35:31)
    at ThemeManager.module.exports.ThemeManager.refreshLessCache (~/AppData/Local/atom/app-1.19.7/resources/app/src/theme-manager.js:411:59)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/theme-manager.js:347:25
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/config.js:627:22
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.19.7/resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.19.7/resources/app/src/config.js:236:20)
    at ThemesPanel.updateThemeConfig (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/settings-view/lib/themes-panel.js:555:27)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/settings-view/lib/themes-panel.js:564:22
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
Hydrogen 1.21.1 
```

**Comment by nomankt** [comment]
+1
