### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/AppData\Local\atom\app-1.20.1\resource...

### ISSUE THREAD

**Issue by 47Phillip** [atom/settings-view#999]
I can't install new packages

1.settings
2.install

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Windows 8.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.251.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Nomedetodos\AppData\Local\atom\app-1.20.1\resources\app\node_modules\settings-view\node_modules\glob\glob.js'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\Users\Nomedetodos\AppData\Local\atom\app-1.20.1\resources\app\node_modules\settings-view\node_modules\glob\glob.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at compileFileAtPath (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:89:29)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at get_glob (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/atom-io-client.js:15:33)
    at AtomIoClient.module.exports.AtomIoClient.cachedAvatar (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/atom-io-client.js:175:20)
    at AtomIoClient.module.exports.AtomIoClient.avatar (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/atom-io-client.js:35:25)
    at PackageCard.loadCachedMetadata (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-card.js:397:25)
    at new PackageCard (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-card.js:74:16)
    at InstallPanel.getPackageCardView (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/install-panel.js:405:20)
    at InstallPanel.addPackageViews (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/install-panel.js:391:55)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/install-panel.js:461:26
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/atom-io-client.js:158:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/install-panel.js:455:27)
    at new InstallPanel (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/install-panel.js:128:16)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/settings-view.js:237:22
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/settings-view.js:361:25)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/settings-view.js:419:30)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/settings-view.js:406:20)
    at SettingsView.addPanel (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/settings-view.js:335:20)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Can you try re-installing and let us know if you still get the same error?

**Comment by jamespatrickwhite** [comment]
Encountered the same issue with an existing Atom installation.  Installation/upgrading of packages result in:
`ENOENT: no such file or directory, open '/opt/atom/resources/app/node_modules/settings-view/node_modules/glob/glob.js'`

Atom version: 1.20.1 x64
OS: Ubuntu 16.04.3 LTS

Looking at the path in the error message, /opt/atom/resources/app exists, but the node_modules directory doesn't appear to be there.

**Comment by rsese** [comment]
> Update: Reinstalling to the latest current version, 1.21.1 x64, appears to have resolved the errors. Package installation and updates work without issue.

Thanks for that update @jamespatrickwhite :+1:

@47Phillip, thanks again for your issue!

We haven't received a response to our question in https://github.com/atom/settings-view/issues/999#issuecomment-331033295. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
